### ISSUE TITLE
use buff on CB it crirical error

### ISSUE THREAD

**Issue by xcelebration** [JoeAlisson/L2jOrg#115]
when use buff on CB it crirical error like some animation issue 
try disable CommunityCastAnimations = False
it still crirical error

Error: 
Protocol: C_PASS_CMD_TO_SERVER(513, 0) <= S_SHOW_BOARD(292, 235) <= S_SHOW_BOARD(292, 235) <= S_SHOW_BOARD(8218, 235) <= C_PWASS_CMD_TO_SERVER(65, 236) <= S_SOCIAL_ACTION(15, 301) <= C_VALIDATE_POSITION(24, 413) <= S_SOCIAL_ACTION(15, 414) <= S_SHOW_BOARD(292, 415) <= S_SHOW_BOARD(292, 415)

History: NCWnd::HideWindow <- NCSliderBar::SetMaxColumn <- NCSliderBar::SetMaxRange <- NCScrollWnd::SetMaxHeight <- NCHtmlViewer::OnPaint <- NCHtmlViewer::DispatchWndMsg <- NCVirtualWndMain::DrawChildWindow <- NCVirtualWndMain::DrawChildWindow <- NCVirtualWndMain::DrawChildWindow <- WM_PAINT <- NCVirtualWndMain::DispatchWndMsg <- NConsoleWnd::ConsolePostRender <- UGameEngine::PostDraw <- ConsolePostRender <- Draw <- UGameEngine::Draw <+ GRenDev = fd940000 <- UWindowsViewport::Repaint <- UWindowsClient::Tick <- ClientTick <- UGameEngine::Tick <- UpdateWorld <- CMainLoop::UpdateTheWorld <- MainLoop

**Comment by vicochips** [comment]
Will look at it :)

**Comment by vicochips** [comment]
Fixed :)
