### ISSUE TITLE
player not have mana auto skill should stop use

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#124]
when not have mana auto skill should stop use

**Comment by vicochips** [comment]
you mean autofarm system?

**Comment by bahamus20** [comment]
yes

**Comment by JoeAlisson** [comment]
I Just test on NA server: 


![shot-na](https://user-images.githubusercontent.com/5034192/79589656-26afb100-80ac-11ea-9d20-d25b859119df.png)
