### ISSUE TITLE
For Bug teleport Dwarven Village - Eastern Mining Zone

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#125]
<teleport id="146" price="1650"> 
        -<location x="169008" y="-208272" z="3496"/>
        +<location x="169008" y="-208272" z="-3496"/>
    </teleport>

**Comment by vicochips** [comment]
I think you forgot something here :D

**Comment by bahamus20** [comment]
<teleport id="146" price="1650"> 
        <location x="169008" y="-208272" z="-3496"/>
    </teleport>

Sorry

**Comment by bahamus20** [comment]
line no. 298 file data/telepoets.xml
location x="169008" y="-208272" z="-3496"

**Comment by JoeAlisson** [comment]
Already Fixed on dd7c41d27828244e7a3cfc49bfbef2ca702baa29
