### ISSUE TITLE
Buff set community board for fight critical error (Only Fight)

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#126]
Gameserver
[WARN ][2020-04-18 21:39:37][ClientPacketHandler:unknownPacket:54]: Unknown Packet (REQUEST_USER_BAN_INFO) : d0 - 00000000 D05E01AA810000                   .^.....
[INFO ][2020-04-18 21:39:41][accounting:runImpl:125]: [Player: HUUU[33194] - Account: singto02 - IP: 127.0.0.1] Logged in
[WARN ][2020-04-18 21:39:53][ClientPacketHandler:unknownPacket:54]: Unknown Packet (EX_REQUEST_CLASS_CHANGE_VERIFYING) : d0 - 00000000 D0660100000000                   .f.....
[WARN ][2020-04-18 21:39:58][ReadHandler:failed:128]: The specified network name is no longer available
java.io.IOException: The specified network name is no longer available
        at java.base/sun.nio.ch.Iocp.translateErrorToIOException(Iocp.java:299)
        at java.base/sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:389)
        at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)

Client
Error: 
Protocol: C_PASS_CMD_TO_SERVER(513, 0) <= S_SHOW_BOARD(292, 99) <= S_SHOW_BOARD(292, 99) <= S_SHOW_BOARD(8218, 99) <= C_PASS_CMD_TO_SERVER(65, 100) <= S_STATUS_UPDATE(18, 126) <= S_COMBAT_MODE_FINISH(7, 177) <= C_VALIDATE_POSITION(24, 228) <= C_VALIDATE_POSITION(24, 229) <= C_VALIDATE_POSITION(24, 234)

History: NCWindowBase::GetParentWnd <- NCWindowBase::IsChildOf <- NCWnd::HideWindow <- NCSliderBar::SetMaxColumn <- NCSliderBar::SetMaxRange <- NCScrollWnd::SetMaxHeight <- NCBBSHtmlViewer::OnPaINT <- NCHtmlViewer::DispatchWndMsg <- NCVirtualWndMain::DrawChildWindow <- NCVirtualWndMain::DrawChildWindow <- NCVirtualWndMain::DrawChildWindow <- WM_PAINT <- NCVirtualWndMain::DispatchWndMsg <- NConsoleWnd::ConsolePostRender <- UGameEngine::PostDraw <- ConsolePostRender <- Draw <- UGameEngine::Draw <+ GRenDev = fd940000 <- UWindowsViewport::Repaint <- UWindowsClient::Tick <- ClientTick <- UGameEngine::Tick <- UpdateWorld <- CMainLoop::UpdateTheWorld <- MainLoop

Exception:
Code [EXCEPTION_READ_VIOLATION  DataAddress:0x000000D2]
Address [0x78B53018]

**Comment by vicochips** [comment]
have you update to last revision ? because it has been fixed

**Comment by bahamus20** [comment]
last rev.

**Comment by vicochips** [comment]
Ok :), we will check it

**Comment by bahamus20** [comment]
Thank you.
