### ISSUE TITLE
alt+g Inventory

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#128]
Chang view alt+g Inventory please.
![Untitled](https://user-images.githubusercontent.com/63811728/79642014-3cfd6000-81c5-11ea-8d8b-5f34f0b62969.png)

Thank you

**Comment by vicochips** [comment]
hey :)

You have wrong client I think. https://i.imgur.com/NpolvHy.png

You should have all this !

**Comment by bahamus20** [comment]
OMG  .. share client to google drive please

**Comment by vicochips** [comment]
I give a link in "wiki" part of the github, it is official client.
