### ISSUE TITLE
Kamael class change missing link html

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#131]
Kamael class change missing link html NPC 31756 and 31757

[WARN ][2020-04-19 21:44:14][HtmCache:getHtmForce:67]: Cache[HTML]: Missing HTML page: data/scripts/quests/org.l2j.scriptsClassMaster/test_server_helper026j.html

**Comment by vicochips** [comment]
I have added them in next commit

**Comment by bahamus20** [comment]
Nice
