### ISSUE TITLE
Critical error kamael class use skill ID 62002

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#132]
Error gameserver
[INFO ][2020-04-19 22:22:52][Item:applyEnchantStats:1728]: applyEnchantStats: Couldn't find option: 80001
[WARN ][2020-04-19 22:22:54][ClientPacketHandler:unknownPacket:54]: Unknown Packet (EX_REQUEST_CLASS_CHANGE_VERIFYING) : d0 - 00000000 D06601C3000000                   .f.....
[WARN ][2020-04-19 22:22:55][ReadHandler:failed:128]: The specified network name is no longer available
java.io.IOException: The specified network name is no longer available
        at java.base/sun.nio.ch.Iocp.translateErrorToIOException(Iocp.java:299)
        at java.base/sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:389)
        at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)

LineageII Crash Report
Error: Assertion failed: Delta==Delta [File:UnPhysic.cpp] [Line: 1297]

Protocol: S_EX_BR_NOTIFY_GAME_POINT(21, 6) <= S_EX_BR_NOTIFY_GAME_POINT(21, 6) <= C_EX_BR_GAME_POINT_REQ(5, 7) <= C_EX_BR_GAME_POINT_REQ(5, 7) <= S_EX_BR_VIP_PRODUCT_LIST_ACK(1480, 8) <= S_EX_LUCKY_GAME_INFO(14, 8) <= C_EX_BR_VIP_PRODUCT_LIST_REQ(5, 8) <= C_EX_REQUEST_LUCKY_GAME_INFO(5, 8) <= S_SKILL_COOL_TIME(7, 10) <= S_MAGIC_SKILL_USE(71, 10)

History: APawn::physWalking <+ werewolf Transient.werewolf Loc.X=118025.000000 Y=-202111.000000 Z=-3840.000000 Acc.X0.000000 Y=0.000000 Z=0.000000 Vel.X=-1.#IND00 Y=-1.#IND00 Z=-1.#IND00 Delta.X=-1.#IND00 Y=-1.#IND00 Z=0.000000 <- APawn::performPhysics <- AActor::Tick <+ Transient.werewolf <- TickAllActors <- ULevel::Tick <+ (NetMode=0) <- UMasterLevel::Tick <- TickLevel <- UGameEngine::Tick <- UpdateWorld <- CMainLoop::UpdateTheWorld <- MainLoop

**Comment by JoeAlisson** [comment]
Seems to be working. Did you use in any specific location ?

![Screenshot from 2020-04-20 12-14-47](https://user-images.githubusercontent.com/5034192/79768046-99b16580-8300-11ea-970c-a827a34fba79.png)

**Comment by bahamus20** [comment]
Outside the city area

**Comment by JoeAlisson** [comment]
Is this issue still happens ?

**Comment by bahamus20** [comment]
Fixed
