### ISSUE TITLE
Help to check. Critical error after teleport to 45010 148000 -3694

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#134]
I am using Client LineageIINA and my system https://drive.google.com/open?id=1uwXK0I92-T74qCqDJTUcX55WwAbMd3d8

DionTerritory.htm
<button action="bypass -h admin_move_to 45010 148000 -3694" width=210>Execution Grounds</button>
Or something wrong?

Error: Assertion failed: Velocity==Velocity [File:UnPhysic.cpp] [Line: 651]

Protocol: S_EX_BR_NOTIFY_GAME_POINT(21, 2) <= S_EX_BR_NOTIFY_GAME_POINT(21, 2) <= C_EX_BR_GAME_POINT_REQ(5, 3) <= C_EX_BR_GAME_POINT_REQ(5, 3) <= S_EX_BR_VIP_PRODUCT_LIST_ACK(1480, 4) <= S_EX_LUCKY_GAME_INFO(14, 4) <= S_SKILL_COOL_TIME(7, 4) <= C_EX_BR_VIP_PRODUCT_LIST_REQ(5, 4) <= C_EX_REQUEST_LUCKY_GAME_INFO(5, 4) <= C_EX_REQUEST_CLASS_CHANGE_VERIFYING(9, 4)

History: APawn::physicsRotation <- APawn::performPhysics <- AActor::Tick <+ Transient.zombie <- TickAllActors <- ULevel::Tick <+ (NetMode=0) <- UMasterLevel::Tick <- TickLevel <- UGameEngine::Tick <- UpdateWorld <- CMainLoop::UpdateTheWorld <- MainLoop

**Comment by vicochips** [comment]
I have seen some problems too on teleport, maybe the new teleport points are not good.

**Comment by JoeAlisson** [comment]
This CE is caused by bad spawn location. We are working on this, but can take time since a lot of data need to be fixed. If you find any other location with this problem, just let me know to fix it.

**Comment by bahamus20** [comment]
Work fine if using system-eu 
https://drive.google.com/open?id=1NuZwWvcEksP0XK-3Sjia-qX_T1sYpItS
