### ISSUE TITLE
admin teleport bug Dion Hills Should be 29928 151415 -2392

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#135]
button action="bypass -h admin_move_to 29928 151415 2392" width=210>Dion Hills</button><br1>

Should be
button action="bypass -h admin_move_to 29928 151415 -2392" width=210>Dion Hills</button><br1>

**Comment by JoeAlisson** [comment]
@bahamus20 issues like this you can open a pull request, I'll be glade to accept it
