### ISSUE TITLE
Wrong material for upgrade EARTH, WIND, WATER SPIRIT but use Fire spirit

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#137]
Wrong material for upgrade EARTH SPIRIT but use Fire spirit

![Shot00008](https://user-images.githubusercontent.com/63811728/79886115-6cf56f00-8422-11ea-91ad-d72e70f1d011.jpg)

**Comment by bahamus20** [comment]
same problem with WIND and WATER

**Comment by vicochips** [comment]
fixed next commit
