### ISSUE TITLE
Soul Finder can't change class to Soul Breaker

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#139]
vicochipsdev
Kamael class 
Soul Finder can't change class to Soul Breaker
test_server_helper020d.html
Button ALIGN=LEFT ICON="NORMAL" action="bypass -h Quest ClassMaster setclass 129
should be
Button ALIGN=LEFT ICON="NORMAL" action="bypass -h Quest ClassMaster setclass 194"

**Comment by vicochips** [comment]
ok fix next commit :)
