### ISSUE TITLE
Over reflect damage

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#141]
Over reflect damage from TARGET
TARGET
1. TARGET player spirit top-grade
2. TARGET player buff reflect damage (skill id 305 song of vengeance)

I think the formula for calculation is wrong.
Formulas.java
return Math.max(0, (base * attack  + baseDamage * 0.3) / Math.log(max(baseDamage, 20)));
May be (not sure)
return Math.max(0, (base  + baseDamage * 0.3) / Math.log(max(baseDamage, 20)));

![Shot00009](https://user-images.githubusercontent.com/63811728/79969089-34ee3a80-84bb-11ea-8561-f88edbab78ac.jpg)
![Shot00010](https://user-images.githubusercontent.com/63811728/79969097-36b7fe00-84bb-11ea-9261-a02f2834fb6a.jpg)

**Comment by vicochips** [comment]
I have made a change next commit

**Comment by bahamus20** [comment]
Rev 1399 vicochipsdev still Over reflect damage
![Shot00002](https://user-images.githubusercontent.com/63811728/79988470-e3ed3f00-84d8-11ea-9af2-1f45c5989e89.jpg)

**Comment by vicochips** [comment]
What is the supposed damages to be received ?

**Comment by bahamus20** [comment]
I think 
return ((base * attack) + (baseDamage * 0.3)) / Math.log(baseDamage);
should be 
return (base + baseDamage * 0.3) / Math.log(baseDamage);

Or anyone else has other ideas?

**Comment by bahamus20** [comment]
Tested with development work fine

Thank

**Comment by bahamus20** [comment]
add to vicochipsdev please

**Comment by bahamus20** [comment]
add to vicochipsdev please
https://github.com/JoeAlisson/L2jOrg/commit/452465723b19417302bd7677a007320081815814

Thank

**Comment by bahamus20** [comment]
development it work fine.
