### ISSUE TITLE
Help please "Java Problem"

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#142]
I using Eclipse 2020-03 Java 14 (C:\Program Files\BellSoft\LibericaJDK-14)

But there is still a problem (I can compile project)
![java](https://user-images.githubusercontent.com/63811728/79993095-9247b300-84de-11ea-9e55-b4ece3324372.jpg)

Thank you

**Comment by vicochips** [comment]
Do you have java home path set on environement variables ?

**Comment by JoeAlisson** [comment]
Try to run the gradle's tasks: cleanEclipse and eclipse.

**Comment by bahamus20** [comment]
Thank
