### ISSUE TITLE
Erro na Quest Q10967_MoreExperience

### ISSUE THREAD

**Issue by spiteridiick** [JoeAlisson/L2jOrg#146]
Quando se chega para iniciar a quest do level 25-30 a mesma não inicia e não se manda nenhuma mensagem de erro no console
![Shot00000](https://user-images.githubusercontent.com/54906606/80163813-b32b0980-85ad-11ea-8a37-5e95a2ab3ba6.jpg)
![Shot00001](https://user-images.githubusercontent.com/54906606/80163814-b45c3680-85ad-11ea-86f7-c615c78035ad.jpg)

**Comment by vicochips** [comment]
Fixed on branch vicochips
