### ISSUE TITLE
Any one share Client or System Protocol 272 please

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#147]
Any one share Client or System Protocol 272 for 127.0.0.1 please

Thank you

**Comment by vicochips** [comment]
This is system from official file, then u put l2.exe in it :)

**Comment by bahamus20** [comment]
How to make l2.exe ?
I tried many hours but without success.

**Comment by bahamus20** [comment]
can't use l2.ini

**Comment by vicochips** [comment]
https://github.com/MobiusDevelopment/L2/releases

Here download it

**Comment by bahamus20** [comment]
Can you share L2FileEdit for l2.ini (Protocol 272) Or your system for 127.0.0.1 ?
My L2FileEdit it not work for system Protocol 272.

Thank

**Comment by vicochips** [comment]
You don't need file edit, it doesnt work anymore to modify l2.ini
You put the l2.exe in system and it works

**Comment by bahamus20** [comment]
Ok Good work 
Thank you.
