### ISSUE TITLE
Teleports Incorretos e falta de mobs

### ISSUE THREAD

**Issue by spiteridiick** [JoeAlisson/L2jOrg#149]
Teleport quando se inicia a quest do lvl 15-20 dark elf e pega o teleport da propria quest vai para o arredores de dark elf vilage, não tem os mobs para matar para fazer a quest. e quando vai teleportar para dark elf vilage. cai em um limbo abaixo da vila.

**Comment by vicochips** [comment]
can you please provide quest name ? :)

**Comment by spiteridiick** [comment]
Q10961_EffectiveTraining e também a Quest Q10964_SecretGarden, depois que você inicia ela, você tem que ir até gorgon flower garden teleportando pra lá você fica no limbo voando nos céus.

**Comment by vicochips** [comment]
I have fixed the teleport problem, I will add the monsters tomorrow :)
