### ISSUE TITLE
Error log Rev 1440 development

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#153]
[debug.log](https://github.com/JoeAlisson/L2jOrg/files/4534639/debug.log)
[game.log](https://github.com/JoeAlisson/L2jOrg/files/4534640/game.log)

**Comment by vicochips** [comment]
Hello :)

You should delete compiled script folder, then relaunch server, warning will deseaper.

**Comment by spiteridiick** [comment]
Os Erros continuam

**Comment by JoeAlisson** [comment]
@spiteridiick Mesmo após deletar a pasta "compiledScripts" de dentro do Gameserver esses erros persistem? 

Essa pasta funciona como um "cache" mas em algumas situações ainda não é possivel que esse cache seja recriado automáticamente, como por exemplo quando um script é renomeado ou removido do Datapack, nessas situações é necessário deletar manualmente para que seja recriado corretamente.

Se mesmo após deletar essa pasta esses erros continuam, pode postar o log por favor ?

**Comment by spiteridiick** [comment]
irei fazer novamente os testes.

**Comment by spiteridiick** [comment]
@JoeAlisson Segue o mesmo erro.
[debug.log](https://github.com/JoeAlisson/L2jOrg/files/4536175/debug.log)

**Comment by spiteridiick** [comment]
@JoeAlisson o projeto tem algum grupo de Whatsapp ou outro pra melhor desenvolver as idéias

**Comment by JoeAlisson** [comment]
@spiteridiick providenciando, logo logo, teremos um canal mais direto pra comunicação. Por enquanto pode falar comigo pelo discord JoeAlisson#4309

Sobre o erro, eu acabei comitando um arquivo de configuração de log por engano no repositório, que fez o erro não ser visível no log. Você pode atualizar e me enviar o log novamente caso o erro persista ?

**Comment by bahamus20** [comment]
No any error on "trunk" but missing 2 line :)

[INFO ][2020-04-27 10:03:33][AuthServerCommunication:connect:58]: Connecting to auth server on /127.0.0.1:9014
[INFO ][2020-04-27 10:03:33][AuthResponse:runImpl:30]: Registered on authserver as 1 [Bartz]

Can login, Can play the game .

**Comment by spiteridiick** [comment]
Nenhum erro mais.
