### ISSUE TITLE
Create a Tutorial 

### ISSUE THREAD

**Issue by HitlerWasJew** [JoeAlisson/L2jOrg#154]
I just found out your project and i am very interested on using it.
But i am totally trash when it comes to Graddle 
I am running the bat and files are generated but i don't know  where to put things.
So yeah i am stuck and without a clue!
Kamael rev 245

**Comment by vicochips** [comment]
Hello !
To compile server: launch gralew distZip
and In the "build" folder, you have .tar and .zip , you can extract it.

**Comment by vicochips** [comment]
I will see with joe to create a wiki with installation process

**Comment by xcelebration** [comment]
use Eclipse IDE download svn and use gradle it very easy

**Comment by HitlerWasJew** [comment]
Vivo if i do this i only get some of the files not all only SQL and Data is there

**Comment by vicochips** [comment]
can u send some screen of what you do ?

**Comment by HitlerWasJew** [comment]
![Screenshot_14](https://user-images.githubusercontent.com/50170744/80310299-9297c500-87e2-11ea-92d4-61c4ac2c2c01.png)
![Screenshot_11](https://user-images.githubusercontent.com/50170744/80310301-93c8f200-87e2-11ea-8365-fc6f02b82068.png)
![Screenshot_12](https://user-images.githubusercontent.com/50170744/80310302-94618880-87e2-11ea-80ae-088f17ffc124.png)
![Screenshot_13](https://user-images.githubusercontent.com/50170744/80310305-94fa1f00-87e2-11ea-8bdb-ac701543aa4f.png)

I cloned the repo and then runned graddle all i get are these files

**Comment by vicochips** [comment]
Do you use gradlew on top of the repo, It seems you runned gradlew just on datapack

**Comment by HitlerWasJew** [comment]
![Screenshot_15](https://user-images.githubusercontent.com/50170744/80310638-709f4200-87e4-11ea-8c24-f97ebe6973d8.png)

I just runned this @vicochips

**Comment by vicochips** [comment]
hmm I think you will find a zip in datapack, one in gameserver, one in authserver.

I don't use this bat to compile. I do it with terminal :D

**Comment by HitlerWasJew** [comment]
I get mixed .zips and tars all over the repo not just on build path.


![Screenshot_16](https://user-images.githubusercontent.com/50170744/80311097-55353680-87e6-11ea-8ef0-dbf395b351d5.png)
![Screenshot_17](https://user-images.githubusercontent.com/50170744/80311099-57979080-87e6-11ea-9bc7-35a55ba97a4a.png)

**Comment by HitlerWasJew** [comment]
So i copy these files to a new folder? really confusing xD

**Comment by vicochips** [comment]
yes because this is default gradlew build, to do it all in one build, you need to add option distZip after gradlew 
https://i.imgur.com/uyXs5og.png

**Comment by HitlerWasJew** [comment]
Well distZip is there but still the same problem i can't find all the files and don't know where to put them and at what order. can someone share his configuration so i can run it via Intelij ? really frustrating

**Comment by vicochips** [comment]
I gave you my conf :p

When I build with distZip I have all in "build -> distribution"

**Comment by vicochips** [comment]
https://i.imgur.com/dgADb87.png

**Comment by HitlerWasJew** [comment]
![Screenshot_18](https://user-images.githubusercontent.com/50170744/80311619-5c117880-87e9-11ea-80f9-c5e19edbdba7.png)
.....

**Comment by vicochips** [comment]
you don't have distZip option here

**Comment by HitlerWasJew** [comment]
![Screenshot_19](https://user-images.githubusercontent.com/50170744/80311759-333db300-87ea-11ea-83d1-8ec731f406fd.png)
not sure if correct

**Comment by vicochips** [comment]
look my image :p https://i.imgur.com/uyXs5og.png

**Comment by HitlerWasJew** [comment]
I just added distZIP and it just generated all the files on the zip THANKS @vicochips Like for real

**Comment by vicochips** [comment]
:p no problem

**Comment by HitlerWasJew** [comment]
Now i have to figure out how to have maria db and mysql at the same system xD

**Comment by HitlerWasJew** [comment]
mysql-installer-community-8.0.19.0 

Will work with this version of the server? @vicochips

**Comment by vicochips** [comment]
I think yes, just try :)

**Comment by HitlerWasJew** [comment]
![Screenshot_20](https://user-images.githubusercontent.com/50170744/80312765-c0cfd180-87ef-11ea-8825-119a66880430.png)
Any possible solutions?

**Comment by HitlerWasJew** [comment]
Installed mysql created a database named l2jd all went ok till this

**Comment by HitlerWasJew** [comment]
Fixed everything and server runs without problems i just need the proper system now xD
I am a pain in the ass i know.
Any download links to download the system?
Kamael rev 245 i downloaded the latest client from official but i need the system

**Comment by vicochips** [comment]
ahaha, nice for the fix :), use  the official system, just put l2.exe in it

**Comment by HitlerWasJew** [comment]
![Screenshot_21](https://user-images.githubusercontent.com/50170744/80313744-a8fb4c00-87f5-11ea-9649-59e5dfc16d5b.png)

L2.exe from what? :D i tried copying one from a patched system and gave me error

**Comment by HitlerWasJew** [comment]
If you could share a working 245 version system ahahaha i SUCK and i know it

**Comment by vicochips** [comment]
use this : https://github.com/MobiusDevelopment/L2/releases

**Comment by HitlerWasJew** [comment]
@vicochips  L2.exe opens and closes again

**Comment by HitlerWasJew** [comment]
L2 anticheat opens as well i only see the splash a black screen and then closes

**Comment by vicochips** [comment]
try this maybe : https://mega.nz/#!98likSra!vP3uaDwJs8oiY5q60UzBSXAbgNELWX_dycWb98Mz96U

**Comment by HitlerWasJew** [comment]
![Screenshot_22](https://user-images.githubusercontent.com/50170744/80314135-55d6c880-87f8-11ea-9f0b-2690eec3bdfd.png)

Doesn't work ether already tried it

**Comment by vicochips** [comment]
well it seems to be a client problem , myself I use official NA client, and I just put l2.exe in it

**Comment by HitlerWasJew** [comment]
Well i used the links in the wiki to download the client and downloaded EU version fml

**Comment by vicochips** [comment]
aaah I yes you have to check america haha

**Comment by vicochips** [comment]
but it should work with EU client if the protocol is 245, some people are using EU client

**Comment by HitlerWasJew** [comment]
I know but every time i try to open l2.exe it just closes. Does anyone have a working system to try?

**Comment by HitlerWasJew** [comment]
It seems its trying to open l2 frost anticheat

**Comment by HitlerWasJew** [comment]
Yeah every time i open it it just randomly closes again and i can't find a shared system anywere

**Comment by vicochips** [comment]
I think it is not system problem, maybe client, you have classic version of client right ? if it is EU it is not the same client for classic and not classic

**Comment by HitlerWasJew** [comment]
this is what i downloaded 

https://eu.4game.com/lineage2/

**Comment by HitlerWasJew** [comment]
I just suck i'll download the proper client

**Comment by HitlerWasJew** [comment]
Hahha now nclauncher wont let me download lineage cause i am in europe....

**Comment by HitlerWasJew** [comment]
![Screenshot_23](https://user-images.githubusercontent.com/50170744/80315533-d0a3e180-8800-11ea-98d8-12b20bffbf89.png)
I hope i am downloading the correct version this time ahahahhaa @vicochips

**Comment by HitlerWasJew** [comment]
Closing the ""Issue"" Here thanks again for your help and keep up the good work ! Add me on discord if you like :) i can help with whatever i can. Empusa#6594
