### ISSUE TITLE
Update L2Store

### ISSUE THREAD

**Issue by JoeAlisson** [JoeAlisson/L2jOrg#157]

**Comment by spiteridiick** [comment]
no L2 Store quando compra algum item não gasta as l2 coins que são pedidas no mesmo.
e os itens não aparecem o mesmo do id. Os itens sãos os corretos mas na loja fica com outra descrição

**Comment by vicochips** [comment]
I have added items on vicochips branch, will pull request soon

**Comment by JoeAlisson** [comment]
see #192
