### ISSUE TITLE
Erro na hora de Compilar

### ISSUE THREAD

**Issue by spiteridiick** [JoeAlisson/L2jOrg#162]
Com a nova atualização que saiu está dando conflito no Pet.Java, pois o mesmo tem uma função chamada Customtype2 é o mesmo eu lendo nas edições foi retirada.

**Comment by JoeAlisson** [comment]
Corigido como o arquivo Pet estava em outro changeset acabou não indo junto com as outras modificações, obrigado por avisar :)

**Comment by spiteridiick** [comment]
Na opção de characteristic-points="13" o maximo é 10 in game, nas opções você pode colocar qualquer numero mas in game só consegue upar 10 características apenas.

**Comment by JoeAlisson** [comment]
Estranho, aqui eu consigo:

![Screenshot from 2020-04-29 14-21-18](https://user-images.githubusercontent.com/5034192/80626505-ef82bd80-8a24-11ea-9606-45f6728ccdac.png)

**Comment by spiteridiick** [comment]
E outra coisa o l2 coins ainda não está consumindo as coins.

**Comment by JoeAlisson** [comment]
Sim, o sistema l2 coin ainda está sendo desenvolvido, pode acompanhar nesse issue #108 .

Conseguiu utilizar mais que 10 caracteristicas ?

**Comment by spiteridiick** [comment]
ainda não fiz o teste estou fazendo um site aqui, mais tarde irei fazer os testes necessários, e outra coisa que percebi que tenho que elogiar que a maioria dos packet que estavam dando erros ao logar no servidor foram resolvidos.
