### ISSUE TITLE
Buffs Improve

### ISSUE THREAD

**Issue by spiteridiick** [JoeAlisson/L2jOrg#174]
Adicionei os Buffs Improve, eles dão os status mas não aparece na barra de skills. segue as xml que fiz delas.
[new 1.txt](https://github.com/JoeAlisson/L2jOrg/files/4589468/new.1.txt)
 

![Shot00000](https://user-images.githubusercontent.com/54906606/81225647-f038c800-8fbf-11ea-92b8-37b1b9912ad5.jpg)
![Shot00001](https://user-images.githubusercontent.com/54906606/81225649-f169f500-8fbf-11ea-8916-acc4bc297a5e.jpg)
![Shot00002](https://user-images.githubusercontent.com/54906606/81225652-f2028b80-8fbf-11ea-94ab-fa95dc5aa8af.jpg)
![Shot00004](https://user-images.githubusercontent.com/54906606/81225655-f29b2200-8fbf-11ea-8ca3-5db7b6f3fce0.jpg)

`

**Comment by spiteridiick** [comment]
e outra coisa também os buffs de over não estão funcionando

**Comment by spiteridiick** [comment]
Um outra coisa que percebi também é SchemeBuffer, quando você adiciona um buff em sua scheme ao invés dele ficar com uma botão - para poder retirar o buff e indicar que você já tem ele em sua scheme ele continua mostrando apenas o botão +

**Comment by spiteridiick** [comment]
@JoeAlisson @vicochips alguem ai tem idéia sobre esse bug? sobre o que fiz de errado

**Comment by vicochips** [comment]
There is no improved buff in classic no?

**Comment by LeonanCarvalho** [comment]
Esses buffs não são originais do classic, embora o cliente tenha suporte os xmls no datapack não existem, vc pode implementar para você mesmo os buffs com base em qualquer revisão H5, recomendo a l2jserver

**Comment by spiteridiick** [comment]
eu implementei eles, coloquei as skills só que o que está acontecendo é que os mesmos dão os status,, só que não aparecem na barra de buffs.

**Comment by spiteridiick** [comment]
> There is no improved buff in classic so I think the client cannot see it

it shows the id's in the buffer shows that they exist but in the buff bar they don't appear

**Comment by vicochips** [comment]
you can add every id you want on the buffer, but if the buff doesnt exist... it will not appear
