### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by spiteridiick** [JoeAlisson/L2jOrg#180]
Um erro um pouco estranho, as vezes quando vai logar com uma char você toma um CE na hora de logar, mas se colocar o char como GM ela loga normalmente, mas se retirar o GM ela volta normalmente a dar CE.
unica coisa que mostra no log é isso.

DEBUG][2020-05-12 01:31:27][EntityHandler:handleType:53]: There is no field with name maxHp on Type org.l2j.gameserver.data.database.data.PlayerData
[DEBUG][2020-05-12 01:31:27][EntityHandler:handleType:53]: There is no field with name maxCp on Type org.l2j.gameserver.data.database.data.PlayerData
[DEBUG][2020-05-12 01:31:27][EntityHandler:handleType:53]: There is no field with name maxMp on Type org.l2j.gameserver.data.database.data.PlayerData
[DEBUG][2020-05-12 01:31:27][EntityHandler:handleType:53]: There is no field with name transform_id on Type org.l2j.gameserver.data.database.data.PlayerData
[DEBUG][2020-05-12 01:31:27][EntityHandler:handleType:53]: There is no field with name deletetime on Type org.l2j.gameserver.data.database.data.PlayerData
[DEBUG][2020-05-12 01:31:27][EntityHandler:handleType:53]: There is no field with name cancraft on Type org.l2j.gameserver.data.database.data.PlayerData
[DEBUG][2020-05-12 01:31:27][EntityHandler:handleType:53]: There is no field with name online on Type org.l2j.gameserver.data.database.data.PlayerData
[DEBUG][2020-05-12 01:31:27][EntityHandler:handleType:53]: There is no field with name char_slot on Type org.l2j.gameserver.data.database.data.PlayerData
[DEBUG][2020-05-12 01:31:27][EntityHandler:handleType:53]: There is no field with name clan_privs on Type org.l2j.gameserver.data.database.data.PlayerData

**Comment by JoeAlisson** [comment]
Não consegui reproduzir o problema. Testei com char recém criado, com um já existente e com GM (tirando e colocando o acess level). Pode postar o erro que dar no cliente ?

**Comment by spiteridiick** [comment]
Version: EP50_Global,CL_s,V2110409,272
BuildDate: Wed Apr 22 22:46:29 2020

Time: 2020.5.12 19:33:50 [GTick=11068,LGTicks=11058,Duration=658]
PosCode: 82920:148691:-3467
ZoneName: Town of Giran
OS: Windows 10(64) 10.0 (Build: 9200), Service Pack 0.0
CPU: GenuineIntel  Intel(R) Core(TM) i3 CPU       M 350  @ 2.27GHz @ 2262 MHz
RAM: 3893MB RAM
CPUInfo: 4,2,4,1
Memory: 298457KB
PrivateMemory: 765880KB
Video: Intel(R) HD Graphics (2900), DX v4.9r904
Option: 1360x693__W0_H0A0K__
Scene: 0_0_0
Stat: 5
Replay: 0_1
WorldRaid: 0_0/0
ClientSocketClosed: 11068
NPAuthSocketClosed: 0
Sev: 1_Bartz
VideoResources: 33 MB
MAC: 6E-52
LANG: ENGLISH
IME: ???

Error: Assertion failed: Location.X != 0.f || Location.Y != 0.f || Location.Z != 0 [File:L2NetNotify.cpp] [Line: 1573]

Protocol: C_REQUEST_SKILL_COOL_TIME(3, 0) <= C_EX_REQUEST_CLASS_CHANGE_VERIFYING(9, 0) <= C_EX_AUTOPLAY_SETTING(21, 0) <= S_EX_VOTE_SYSTEM_INFO(25, 1) <= S_SKILL_COOL_TIME(7, 1) <= S_L2_FRIEND_LIST(7, 1) <= S_EX_STORAGE_MAX_COUNT(53, 1) <= S_EX_PCCAFE_POINT_INFO(23, 1) <= S_EX_USER_BOOST_STAT(9, 1) <= S_ABNORMAL_STATUS_UPDATE(5, 1)

History: UGameEngine::OnUserInfo <- UIPacket_OnUserInfo_2 <+ OldPos=(0:0:0), CurPos:(0:0:0) <- Setting 2 <- UIPacket <- ClientCmd <+ size:126, disassem:8 <- UNetworkHandler::Tick <+ Protocol Name=S_USER_INFO <- UGameEngine::Tick <- UpdateWorld <- CMainLoop::UpdateTheWorld <- MainLoop


Agora se o char é gm loga normalmente
