### ISSUE TITLE
Clan crest

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#184]
Don't work clan crest, when installing a picture, a game server error.

**Comment by bahamus20** [comment]
After first install a picture success but can't change picture ( Set crest or delete crest  and set new picture) still same picture  first installed

**Comment by bahamus20** [comment]
Rev 1931
After first install a picture success but can't change picture ( Set crest or delete crest and set new picture) still same picture first installed

**Comment by bahamus20** [comment]
Fixed
