### ISSUE TITLE
VIP Itens

### ISSUE THREAD

**Issue by spiteridiick** [JoeAlisson/L2jOrg#185]
No projeto tem uns itens que teoricamente, deveriam aumentar os pontos VIP mas olhei nele e eles não estão funcionando gostaria de saber como deveria fazer para que eles funcionem pois fui nas skills dos mesmos e nenhum estão corretos, devo colocar como GainVipPoints?
ou algo assim?

ID's de alguns

<item id="71314" name="VIP Scroll - 800" type="SCROLL" icon="BranchIcon.Icon.g_bm_vip_potion_i00">
	
		<restriction freightable="false" stackable="true" tradable="false" dropable="false" sellable="false" private-sellable="false" depositable="false"/>
		<attributes weight="5" action="SKILL_REDUCE_ON_SKILL_SUCCESS"/>
	</item>

	<item id="71315" name="VIP Scroll - 2400" type="SCROLL" icon="BranchIcon.Icon.g_bm_vip_potion_i00">
	
		<restriction freightable="false" stackable="true" tradable="false" dropable="false" sellable="false" private-sellable="false" depositable="false"/>
		<attributes weight="5" action="SKILL_REDUCE_ON_SKILL_SUCCESS"/>
	</item>

	<item id="71316" name="VIP Scroll - 80" type="SCROLL" icon="BranchIcon.Icon.g_bm_vip_potion_i00">
	
		<restriction freightable="false" stackable="true" tradable="false" dropable="false" sellable="false" private-sellable="false" depositable="false"/>
		<attributes weight="5" action="SKILL_REDUCE_ON_SKILL_SUCCESS"/>
	</item>

	<item id="71317" name="VIP Scroll - 240" type="SCROLL" icon="BranchIcon.Icon.g_bm_vip_potion_i00">
	
		<restriction freightable="false" stackable="true" tradable="false" dropable="false" sellable="false" private-sellable="false" depositable="false"/>
		<attributes weight="5" action="SKILL_REDUCE_ON_SKILL_SUCCESS"/>
	</item>

**Comment by JoeAlisson** [comment]
Ainda não existe suporte para adicionar pontos por skill. 
Para implementar é necessário criar um efeito para skill que adicione esses pontos ao player. Nos items é necessário adicionar um skill reducer para a respectiva skill.

**Comment by MaJr-Dp** [comment]
Whatever, do not score ))

**Comment by JoeAlisson** [comment]
This will be addressed on #204
