### ISSUE TITLE
Soul charges and spirit charges do not appear in the auto-use icons

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#187]
Soul charges and spirit charges do not appear in the auto-use icons, they are used from the panel
![image](https://user-images.githubusercontent.com/65304566/81864541-741d2200-9575-11ea-9805-70abc65de8a4.png)

**Comment by vicochips** [comment]
hello !
Do you have the official NA client ? And last rev from development ?

**Comment by expert43** [comment]
Official ru client 272 protocol classic, Rev release 1.4.0

**Comment by JoeAlisson** [comment]
Already fixed. See #160

**Comment by expert43** [comment]
Good day, as I understand it is already fixed in "added this to the r1.4.0 milestone" but I have this build and does not work, can you tell me what the problem is?

**Comment by vicochips** [comment]
I think it is not on the released version. But in the development's one

**Comment by expert43** [comment]
ok
