### ISSUE TITLE
Incorrect display of gain percentages

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#188]
Incorrect display of gain percentages, in this case 2 scrolls of 30% are used and shows 3030%)))
![image](https://user-images.githubusercontent.com/65304566/81865020-1210ec80-9576-11ea-9999-06b12f8e9de5.png)

**Comment by JoeAlisson** [comment]
Did you changed the exp rate on config ?

**Comment by expert43** [comment]
no change

**Comment by vicochips** [comment]
In my client with this scroll I have no issue, how can we reproduce it ?

**Comment by expert43** [comment]
there used 2 scrolls on 30% different

**Comment by JoeAlisson** [comment]
Is this issue happening yet ?

**Comment by expert43** [comment]
at the moment everything is working, I will close it
