### ISSUE TITLE
Erros após att

### ISSUE THREAD

**Issue by spiteridiick** [JoeAlisson/L2jOrg#195]
Mesmo após deletar a pasta compiledscripts o erro persiste.
E tá faltando a sql forum.sql.
[debug.log](https://github.com/JoeAlisson/L2jOrg/files/4632193/debug.log)

**Comment by JoeAlisson** [comment]
Pode testar com a nova versão?
O suporte ao antigo sistema de Forum Manager, que não estavam sendo usados, foram removidos, então as tabelas que faziam parte desse sistema também foram removidas
