### ISSUE TITLE
Dragon pendant Polish

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#196]
Dragon pendant Polish that doesn't break the suspension, breaks it
`	<item id="49470" name="Shining Pendant Varnish" type="SOLID_ENCHANT_ARMOR" icon="icon.bm_pendant_varnish_premium">
	
		<restriction freightable="false" stackable="true" dropable="false" sellable="false" depositable="false"/>
		<attributes immediate-effect="true" action="SKILL_REDUCE"/>
		<action handler="EnchantScrolls"/>
	</item>`
![image](https://user-images.githubusercontent.com/65304566/82062667-1dc5f580-96d3-11ea-8510-12d22af439bb.png)

**Comment by vicochips** [comment]
Hello. 

I think fire water etc pendant’s are not anymore used on kamael

Can you test with dragon’s Pendant attack ?

**Comment by vicochips** [comment]
fix on vicochips for brillant pendant varnish
