### ISSUE TITLE
Spoil doesn't work

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#198]
Spoil doesn't work, mobs don't turn blue

**Comment by expert43** [comment]
development

**Comment by expert43** [comment]
Or rather mobs spoiled, but not turning blue, if he use the ability to assign lack of items and adena)))))

**Comment by expert43** [comment]
![image](https://user-images.githubusercontent.com/65304566/82079828-2ecf3080-96ec-11ea-9c0f-c585c1650460.png)

**Comment by vicochips** [comment]
Hey :)

On what monsters did u try ?

**Comment by expert43** [comment]
the initial location of Gludio

**Comment by expert43** [comment]
the corrected spoiler is already included in Development? if so, it also doesn't work

**Comment by expert43** [comment]
mobs don't turn blue

**Comment by JoeAlisson** [comment]
Still in progress, I start but I ran out of time. soon I'll go back to fix it

**Comment by expert43** [comment]
Ok, good lob )
