### ISSUE TITLE
Skill clan

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#199]
I studied the clan skills at level 5, after restarting the server, they disappeared
![image](https://user-images.githubusercontent.com/65304566/82088499-8c6a7980-96fa-11ea-94bd-5d870926d952.png)
![image](https://user-images.githubusercontent.com/65304566/82088795-11ee2980-96fb-11ea-870c-87b0f366b5e6.png)

**Comment by expert43** [comment]
after relog, the clan leader remained a clan of skill, the rest of the members left a couple of skills
![image](https://user-images.githubusercontent.com/65304566/82490407-dfbe3c80-9aeb-11ea-9f4e-ec84ffd44bcf.png)
![image](https://user-images.githubusercontent.com/65304566/82490503-09776380-9aec-11ea-9c17-57b17d176920.png)
![image](https://user-images.githubusercontent.com/65304566/82490563-20b65100-9aec-11ea-8256-7e460a66e702.png)
also on the screenshot you can see that there is skill Abundance of the clan in the tab rewards, but it is not in the passive skills of the character

**Comment by expert43** [comment]
![image](https://user-images.githubusercontent.com/65304566/82586998-20c45880-9ba1-11ea-89eb-6fa03fbb312f.png)

**Comment by expert43** [comment]
this is a different character from the same clan
![image](https://user-images.githubusercontent.com/65304566/82587121-45b8cb80-9ba1-11ea-8d87-520a4251f7c0.png)

**Comment by JoeAlisson** [comment]
I can't reproduce it. I tried these:
-Learn the clan skills -> all current members receive it.
-Add new member -> He received the skills
-Leave from clan -> He lost the skills
-Restart the server -> All members still with the skills
-Remove the skills from database -> all members lost the skills.

Can you help me to reproduce it ? Is there something else that I  have  to do ?


![Screenshot from 2020-05-21 18-38-56](https://user-images.githubusercontent.com/5034192/82613488-c674c900-9b9b-11ea-85e1-e43a02445deb.png)

**Comment by expert43** [comment]
Well, today we will check again, I will unsubscribe

**Comment by vicochips** [comment]
maybe with clan level 5 ?

**Comment by expert43** [comment]
Yes clan level 5

**Comment by expert43** [comment]
have 2nd individual in clan
![image](https://user-images.githubusercontent.com/65304566/82649393-ccad8880-9c21-11ea-9b2a-d621069d9029.png)

**Comment by expert43** [comment]
Now I have taught skills through the admin menu
![image](https://user-images.githubusercontent.com/65304566/82649935-9e7c7880-9c22-11ea-930b-9d96ffbbecbd.png)
and this is the 2nd character in the clan
![image](https://user-images.githubusercontent.com/65304566/82650015-be13a100-9c22-11ea-8e51-1ef8e6d0e6d9.png)

**Comment by JoeAlisson** [comment]
I think, I understood your problem. Is not a bug. These skills has precondition based on social class. So it only is applyed on characters that meet the requirements. 

I couldn't yet reproduce missing skills on clan info.

**Comment by expert43** [comment]
> I think, I understood your problem. Is not a bug. These skills has precondition based on social class. So it only is applyed on characters that meet the requirements.
> 
> I couldn't yet reproduce missing skills on clan info.

When you learn skills from NPCs they are not in the "clan" tab

**Comment by expert43** [comment]
https://github.com/JoeAlisson/L2jOrg/issues/199#issuecomment-632576571

**Comment by JoeAlisson** [comment]
Yes, I learned from NPC. Still can't reproduce :/


https://www.youtube.com/watch?v=WbH3wvcCFpQ
