### ISSUE TITLE
Reflect

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#205]
Practically from all mobs you get retaliatory damage from yourself, you die from your attack
![image](https://user-images.githubusercontent.com/65304566/82153888-f148df80-9872-11ea-9610-2025431119ea.png)

**Comment by expert43** [comment]
It seems that only with the Kamael race

**Comment by vicochips** [comment]
I tried with level 42 soul breaker, and I dont have any issue, can u try again or tell me how to reproduce?

**Comment by expert43** [comment]
> I tried with level 42 soul breaker, and I dont have any issue, can u try again or tell me how to reproduce?

Create a 40 SB teach him all the skills and hit auto attack mobs

**Comment by expert43** [comment]
the problem is his skill, so when SB borrows buffs the enemy, the soul is transferred to the enemy
