### ISSUE TITLE
augmentation

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#207]
Under argumentation physical weapons ordinary stone life from 20 stones 20 active and passive skills

**Comment by MaJr-Dp** [comment]
The problem in your request is not clear!
The system of Agumentation is not completed.

**Comment by MaJr-Dp** [comment]
New system:
https://forums.lineage2.com/topic/19231-tales-untold-preliminary-patch-notes-classic-server/?tab=comments#comment-130333
