### ISSUE TITLE
Chance enchant

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#208]
Add the ability to set the chances of sharpening for each level, for example, an earring
enchant "1" chance="100"
enchant "2" chance="100"
enchant "3" chance="100"
enchant "4" chance="50"
enchant "5" chance="40"
etc
now as do not put the odds, still on 4 sharpens 100%

          
	<enchantRateGroup name="JEWEL_GROUP">	
		<enchant until="1" chance="100" />		
		<enchant until="2" chance="100" />
		<enchant until="3" chance="100" />
		<enchant until="4" chance="40" />		
		<enchant until="5" chance="30" />
		<enchant until="6" chance="20" />
		<enchant until="7" chance="15" />
		<enchant until="8" chance="13" />
		<enchant until="9" chance="11" />		
		<enchant until="10" chance="9" />
		<enchant until="11" chance="7" />
		<enchant until="12" chance="6" />
		<enchant from="13" until="16" chance="5" />
	</enchantRateGroup>

**Comment by expert43** [comment]
<enchantRate group="JEWEL_GROUP">
			<item slot="NECK" /> 
			<item slot="EAR" /> 
			<item slot="FINGER" /> 
		</enchantRate>

**Comment by JoeAlisson** [comment]
Related to  #88
