### ISSUE TITLE
Error when excute rankers (sql)

### ISSUE THREAD

**Issue by phamminh88** [JoeAlisson/L2jOrg#212]
I am getting an error when I create rankers in mysql. 
/ * SQL Error (4018): No order list in window specification for 'rank' * /
I using HediSQL for create DB

**Comment by vicochips** [comment]
Hello :)

What version of mysql do u use ?

**Comment by phamminh88** [comment]
i using mysql 8.0

**Comment by bahamus20** [comment]
https://www.appserv.org/en/
