### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by extysecz** [JoeAlisson/L2jOrg#214]
Quest CollectSpiderweb on Elven character It does not add a count when killed.

Cultured Adventurer quest kill 300 mobs , I kill one mob and quest complete (all races) (CLOSE)

**Comment by vicochips** [comment]
Hello, for cultured adventurern Do you test has a gm ?

Because if yes, it is normal so : 

`if (killer.isGM())
			{
				qs.setCond(2, true);
				qs.unset(KILL_COUNT_VAR);
				killer.sendPacket(new ExShowScreenMessage(NpcStringId.MONSTERS_OF_THE_ABANDONED_CAMP_ARE_KILLED_NUSE_THE_TELEPORT_TO_GET_TO_BATHIS_IN_GLUDIO, 2, 5000));
			}`

**Comment by extysecz** [comment]
yeah of course, my bad.
