### ISSUE TITLE
AutoPlay

### ISSUE THREAD

**Issue by spiteridiick** [JoeAlisson/L2jOrg#215]
AutoPlay está com o delay de Cast Skills muito alto, a skill já recarregou mas o player não bate tem um delay de 3 a 4 segundos para um próximo ataque.
E uma Outra sugestão que tenho pra dar é uma forma do AutoPlay de usar a ManaPotion, pois se colocar um Mago para usar o autoplay ele fica sem mana muito rápido.

**Comment by JoeAlisson** [comment]
Com relação a mana potion, eu não me recordo de ter visto no cliente uma que seja utilizável no  auto play. Visto que o cliente não tem suporte para adicionar mana potion separadamente, e assumindo que essa mana que está falando é custom, acredito que o melhor modo de evitar que seja usada tão rápido é colocando um delay no item.

 Caso exista uma mana potion que seja utilizável no autoplay, pode me falar o Id ?

**Comment by spiteridiick** [comment]
Não tem uma que é auto utilizável, eu gostaria de saber se tem como implementar visto que o consumo de mana é auto, eu mesmo tentei fazer com que ela se tornasse auto utilizável e não consegui.

**Comment by spiteridiick** [comment]
agora em relação do problema do delay de ataques eu fiz um vídeo para explicar melhor o problema
https://vimeo.com/user116100881/review/421383720/b4befb2c63

**Comment by JoeAlisson** [comment]
talvez apenas adicionar o atributo auto-use="SUPPLY" seja suficiente. Mas não testei se precisa de mais algum ajuste.

Não consigo ver o vídeo. O Auto play é ativado a cada 2 segundos, então de uma ação pra outra ele geralmente demora esse tempo. Mas pode ter um pequeno delay, já que não é uma thread com alta prioridade. Outra coisa que pode acontecer é que ao passar os 2 segundos a ação anterior ainda esteja em andamento, então ele só irá fazer a próxima ação em 2 segundos, o que as vezes pode dar a impressão que passou um pouco mais.

De toda forma eu fiz o commit  6eb1030  para tentar reduzir essa sensação, pode testar pra ver se surtil efeito?

**Comment by spiteridiick** [comment]
Eu testei auto-use="supply" não funcionou, e sobre o commint do auto-play não alterou nada, continua com um delay muito grande de atk de skill, algo em torno de 5 a 6 segundos.

**Comment by JoeAlisson** [comment]
Então, acredito que necessita de suporte no client para funcionar.
