### ISSUE TITLE
RB Jewels Drop

### ISSUE THREAD

**Issue by extysecz** [JoeAlisson/L2jOrg#216]
There are no RB jewelry drop (Orfen,Core,Zaken,Antharas,Baium). But in the drop list are shown.

**Comment by vicochips** [comment]
Hello.

Well, chance is not 100% no ?

**Comment by extysecz** [comment]
Yeah it says 100% chance in droplist (shift+click and droplist)

**Comment by vicochips** [comment]
I think shift + click is bugged

Chance in datapack is 20%

**Comment by extysecz** [comment]
Ohh ok.. then close

**Comment by extysecz** [comment]
10 times rbs killed and no rb jewels..

**Comment by vicochips** [comment]
Ahaa 
Can u tell me what if of rb you killed?

**Comment by extysecz** [comment]
hey, queen ant in ant nest and orfen in sea of spore..

**Comment by extysecz** [comment]
still nothing..

**Comment by vicochips** [comment]
Yeah it seems to have a problem with queen ant and orfen, I investigate why (maybe because gm, level etc)

**Comment by extysecz** [comment]
I tried with GM and without GM with small level and higher level, no rb jewelry drop (orfen,queen,antharas,core.,zaken)
