### ISSUE TITLE
The Olympiad doesn't work

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#218]
Output information that is not clear at all
![image](https://user-images.githubusercontent.com/65304566/82492219-80adf700-9aee-11ea-977f-61111329d489.png)
![image](https://user-images.githubusercontent.com/65304566/82492268-958a8a80-9aee-11ea-82da-ffab2f7ffefc.png)

**Comment by JoeAlisson** [comment]
see #93
