### ISSUE TITLE
Ranks

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#219]
There are no bonuses for first places in the ranks
![image](https://user-images.githubusercontent.com/65304566/82492444-e306f780-9aee-11ea-8197-a7d984748210.png)

**Comment by vicochips** [comment]
You have to wait 1 day for the skills to be working :).

After that, skills works as expected.

**Comment by expert43** [comment]
Ok) good job 👌👍👏

**Comment by expert43** [comment]
check and close then)
