### ISSUE TITLE
Can't add rune to weapon

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#222]
Can't add rune to weapon
![Shot00016](https://user-images.githubusercontent.com/63811728/82566151-b19d3300-9ba5-11ea-98e8-89cb272c978b.jpg)

**Comment by extysecz** [comment]
hm.. for me its working.. 
![image](https://user-images.githubusercontent.com/23057968/82567283-738c1900-9b7d-11ea-95ed-31f0f58a617d.png)

**Comment by bahamus20** [comment]
My item
[WARN ][2020-05-21 21:28:57][RequestItemEnsoul:runImpl:153]: Player: Player:ORG[39569] attempting to ensoul item option that doesn't exists! (unknown fee)
[WARN ][2020-05-21 21:29:54][RequestItemEnsoul:runImpl:153]: Player: Player:ORG[39569] attempting to ensoul item option that doesn't exists! (unknown fee)

**Comment by vicochips** [comment]
I have just test with the same runes , and it works for me.

What weapon did u use ?

**Comment by bahamus20** [comment]
not work with S Weapon.
Just tested with weapon A. It works.

**Comment by vicochips** [comment]
Fix on vicochips dev, I will pull request soon
