### ISSUE TITLE
Missing cloak skill

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#223]
[INFO ][2020-05-21 21:31:26][Item:applyEnchantStats:1712]: applyEnchantStats: Couldn't find option: 80077
![Shot00018](https://user-images.githubusercontent.com/63811728/82569500-8701a900-9baa-11ea-9cad-04083f3b8c0d.jpg)

**Comment by spiteridiick** [comment]
Estou resolvendo esse erro.

**Comment by bahamus20** [comment]
> Estou resolvendo esse erro.

thank you

**Comment by spiteridiick** [comment]
Vai ai algumas edições que estou fazendo em breve estará tudo ok.
Um único fato que não consegui foi que as Capas Sayha Supreme alterasse a aparencia da skill passiva conforme fosse enchantando

**Comment by vicochips** [comment]
Added on develop
