### ISSUE TITLE
Wrong slot dragon pendent

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#224]
Wrong slot dragon pendent
![Shot00019](https://user-images.githubusercontent.com/63811728/82569704-cfb96200-9baa-11ea-9965-6749d9ff9f95.jpg)
![Shot00020](https://user-images.githubusercontent.com/63811728/82569715-d21bbc00-9baa-11ea-8089-8b7298d59b8b.jpg)

**Comment by vicochips** [comment]
In this rev of Classic kamael, there is no more fire water etc pendant no?
Just pendant attack and magic attack

**Comment by bahamus20** [comment]
Thank you
