### ISSUE TITLE
L2 coin not update on inventory

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#225]
L2 coin not update on inventory

My inventory empty L2 coin.
Need to Restart game
![Shot00021](https://user-images.githubusercontent.com/63811728/82570393-b9f86c80-9bab-11ea-8eed-4bb936f397d9.jpg)
![Shot00022](https://user-images.githubusercontent.com/63811728/82570406-bebd2080-9bab-11ea-89d6-8ab98adeee66.jpg)
![Shot00023](https://user-images.githubusercontent.com/63811728/82570423-c2e93e00-9bab-11ea-8f89-9d4faa1316f8.jpg)

**Comment by JoeAlisson** [comment]
see #108
