### ISSUE TITLE
Missing skill boss jewel level 4

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#227]
Missing skill boss jewel level 4
![Shot00025](https://user-images.githubusercontent.com/63811728/82632938-f798dc00-9c23-11ea-8fca-a552fcc7d774.jpg)

**Comment by extysecz** [comment]
Hey, Where can I find this admin menu find item tool?

**Comment by bahamus20** [comment]
alt+g  
or
http://forum.ragezone.com/f343/l2-gm-commands-180654/

**Comment by MaJr-Dp** [comment]
Done
