### ISSUE TITLE
Rank

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#228]
Good morning) the reporter was closed early, there were no effects, it took 2 days. Or is it just me?)
![image](https://user-images.githubusercontent.com/65304566/82638991-826fdb80-9c10-11ea-9c9a-3b92b86d3938.png)

**Comment by vicochips** [comment]
Hello,

Was the server ON at 6:30 am ?

 <schedule name="reset" hour="06" minute="30">
                <event name="#onReset"/>
            </schedule>

every scheduled task resets at 6:30 am, server must be ON

**Comment by expert43** [comment]
No the server is disabled at this time)
