### ISSUE TITLE
Crafting system

### ISSUE THREAD

**Issue by AliEn-ST** [JoeAlisson/L2jOrg#234]
hello, dwarves do not have the crafting ability, and when you manually assign it and put dwarf lv 84 it does not receive the rate and critical creation bonus

**Comment by vicochips** [comment]
Hello, 

what do you mean ?  there is the darwen workshop in "actions"

**Comment by AliEn-ST** [comment]
no, dwarven dont have skill dwarf create item in skills (actives)

**Comment by AliEn-ST** [comment]
i fix adding the skill 172 in skill trees

**Comment by vicochips** [comment]
Oh ok I didn’t Understood.

So strange it was not on skilltree :O

**Comment by AliEn-ST** [comment]
yeah, and skill master of creation and critical creation dont work xD

**Comment by AliEn-ST** [comment]
my english its bad, srry :/

**Comment by vicochips** [comment]
Np
I will look at it

**Comment by vicochips** [comment]
@AliEn-ST The skill craft item is not active skill it is passiv skill, he was on skill tree already

Same as master creation and critical creation
