### ISSUE TITLE
Help to fix "Java Problem" please.

### ISSUE THREAD

**Issue by gskillact** [JoeAlisson/L2jOrg#236]
I imported branches\development
and found "Java Problem"

I am using 
1. Windows 10

2. Eclipse IDE for Java Developers
Version: 2020-03 (4.15.0)
Build id: 20200313-1211

3. Java jdk-14

Or guide for import to eclipse.

![02](https://user-images.githubusercontent.com/65797042/82719753-a34f3400-9cd7-11ea-92f1-318054ea727b.png)

![01](https://user-images.githubusercontent.com/65797042/82719752-a1857080-9cd7-11ea-8d8d-8e21d784c474.png)

Thank you for answer.

**Comment by AliEn-ST** [comment]
i use intellij idea ultimate, its better to me, and check java_home, and jre_home
![2](https://user-images.githubusercontent.com/65177896/82720214-3f991c80-9c7f-11ea-898b-b36e5bd3f35e.PNG)
![1](https://user-images.githubusercontent.com/65177896/82720217-4162e000-9c7f-11ea-86c0-fb726628e6b0.PNG)

**Comment by AliEn-ST** [comment]
delete all another java versions, use only openjdk 14.0.1

**Comment by gskillact** [comment]
Thank you.
I using eclipse. still have problem.
Trying to use intellij idea ultimate.

**Comment by gskillact** [comment]
intellij idea ultimate too difficult for me.. Give up for intellij idea ultimate

**Comment by gskillact** [comment]
Any one share guide for eclipse please.
Thank.

**Comment by JoeAlisson** [comment]
see if these can help you:
#99 
#142

**Comment by gskillact** [comment]
Thank for all.
I am give up.

**Comment by bahamus20** [comment]
Don't worry. 
I also the same problem. But it works fine. can compile.
