### ISSUE TITLE
Antharas skip waiting time error

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#240]
[WARN ][2020-05-23 23:34:55][AdminCommandHandler:lambda$useAdminCommand$0:94]: Exception during execution of admin_grandboss_skip 29068: java.lang.NullPointerException

![Shot00051](https://user-images.githubusercontent.com/63811728/82735756-332fc500-9d4e-11ea-9db7-391d88fb8175.jpg)

**Comment by JoeAlisson** [comment]
See #335
