### ISSUE TITLE
Spoil

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#243]
![image](https://user-images.githubusercontent.com/65304566/82760973-e5739500-9dff-11ea-8180-ecbc64f5b277.png)
I think that the topic with the spoiler was closed early, but now the mob is blue when spoiling, but now the chance of spoiling has become 100% and the mob is blue in 100% of the case, although it should only be when you can get items from it

**Comment by JoeAlisson** [comment]
The Issue was closed automatically when the milestone ended. In those case, you can reopen it without any problem.

**Comment by expert43** [comment]
ok)

**Comment by expert43** [comment]
is there any movement in this direction?))
