### ISSUE TITLE
Share quest with party

### ISSUE THREAD

**Issue by extysecz** [JoeAlisson/L2jOrg#247]
Share quest with party for killing 200-300-500 monsters. Can you allow that?

**Comment by vicochips** [comment]
Is it custom? In official you don't share quest with party no ?

**Comment by extysecz** [comment]
hey, on essence europe it is allowed.

**Comment by vicochips** [comment]
hmm, 
Actually the source is based on NA classic official, not essence. I will let joe decide for this, maybe we will create a config for this.

**Comment by extysecz** [comment]
Okey.

**Comment by AliEn-ST** [comment]
in NA classic official thats are allowed xD

**Comment by vicochips** [comment]
Ok I will test and I will change quests so :)

**Comment by vicochips** [comment]
But it is working on party here, just the killer have the item

**Comment by extysecz** [comment]
Yeah, on ncsoft so party members get it too.

**Comment by Bru7aLMike** [comment]
The fix has been prepared. Awaiting deployment.
