### ISSUE TITLE
Superior Dye 3 Job

### ISSUE THREAD

**Issue by cleidsonh** [JoeAlisson/L2jOrg#248]
the Dyes does not appear, I have already fixed items / 49000-49999.xml and also HennaList.xml, even so it does not work

**Comment by vicochips** [comment]
Hello, where did u fix this items ? On what branch ? local ?

**Comment by cleidsonh** [comment]
local
I put the missing tags in the item's xml
[Imagem 49000-49999.xml](https://imgur.com/xfP0Wob)

and HennaList.xml

> 
        <henna dyeId="289" dyeName="bestdye_s4c4_c" dyeItemId="49971" dyeLevel="76">
        <stats str="4" con="-4" dex="0" int="0" men="0" wit="0" luc="0" cha="0"/>
        <wear count="10" fee="628000"/>
        <cancel count="5" fee="125600"/>
        <classId>88</classId> 
        <classId>89</classId> 
        <classId>90</classId> 
        <classId>91</classId> 
        <classId>93</classId> 
        <classId>92</classId> 
        <classId>94</classId> 
        <classId>95</classId> 
        <classId>96</classId> 
        <classId>97</classId> 
        <classId>98</classId> 
        <classId>99</classId> 
        <classId>100</classId> 
        <classId>101</classId> 
        <classId>102</classId> 
        <classId>103</classId> 
        <classId>104</classId> 
        <classId>105</classId> 
        <classId>106</classId> 
        <classId>107</classId> 
        <classId>108</classId> 
        <classId>109</classId> 
        <classId>110</classId> 
        <classId>111</classId> 
        <classId>112</classId> 
        <classId>113</classId> 
        <classId>114</classId> 
        <classId>115</classId> 
        <classId>116</classId> 
        <classId>117</classId> 
        <classId>118</classId> 
	 <classId>131</classId> 
        <classId>195</classId> 
        <classId>134</classId> 
    </henna>

[result](https://imgur.com/zUO0EjH)

**Comment by vicochips** [comment]
what is your class in game? :)

**Comment by cleidsonh** [comment]
I tested with Trickster and Maestro

**Comment by cleidsonh** [comment]
I tested with Trickster and Maestro

**Comment by vicochips** [comment]
In maestro level 80: 

https://i.imgur.com/1HiJdA0.png

**Comment by vicochips** [comment]
Do you have the full Hennalist with the classId, or u just did this dye?
