### ISSUE TITLE
Passive Skill Clan Fortune

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#249]
After passing the clan arena gave Passive Skill Clan Fortune but it is not displayed in the skills and gives an error game server
[WARN ][2020-05-26 14:13:41][EffectList:addPassive:835]: Passive Skill Clan Fortune (392, 3) with abnormal type: EXP_SP_A!

**Comment by JoeAlisson** [comment]
This warn shouldn't cause any issue, but I'll look at it

**Comment by expert43** [comment]
Simply this skill there is no in the list my passive skills, although a skill received for clan arena

**Comment by MaJr-Dp** [comment]
Done
