### ISSUE TITLE
stairs giran castle

### ISSUE THREAD

**Issue by doulu99** [JoeAlisson/L2jOrg#251]
how do I cast the artifact if there are no stairs...cause i cant cast the artifact

https://ibb.co/xYStRZ2

**Comment by spiteridiick** [comment]
Eu fiz a siegue para testar só tem como sumonar após vc matar o governador  Barão Lewin Waldner, e após isso de um hit no artefato e pode sumoná-lo livremente.

**Comment by doulu99** [comment]
> Eu fiz a siegue para testar só tem como sumonar após vc matar o governador Barão Lewin Waldner, e após isso de um hit no artefato e pode sumoná-lo livremente.

have you test cancel cast and cast again?

**Comment by JoeAlisson** [comment]
The stairs doesn't exist anymore. The whole Siege system needs to be reworked.
See #100
