### ISSUE TITLE
Chance and spoilage penalty

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#253]
I 60 LVL can zaspoylit with 100% chance Moba 3 LVL and assign drop, so should not be, should be a fine. So same mob turns blue but with him can not will be assigned spoyl and can and will be assigned, should turn blue only when can be assign

**Comment by expert43** [comment]
![image](https://user-images.githubusercontent.com/65304566/83017647-af672880-a02c-11ea-8989-00a43ee4c209.png)

**Comment by expert43** [comment]
![image](https://user-images.githubusercontent.com/65304566/83017776-e9d0c580-a02c-11ea-9cfb-1f09b962db05.png)

**Comment by JoeAlisson** [comment]
related #243
