### ISSUE TITLE
eva hats cannot be enchanted

### ISSUE THREAD

**Issue by AliEn-ST** [JoeAlisson/L2jOrg#260]
when i fix the bug the hat dont give me the enhanced effect
the bug are in xml 70700-70799, hat are in "enchant enabled : false"
and not all hats give the +1, gatekkeper hat for example

**Comment by vicochips** [comment]
Hello, I have done a fix for enchantment,

But gatekeeper hat is not a hat to be enchanted: 

https://l2central.info/classic/%D0%A3%D0%BA%D1%80%D0%B0%D1%88%D0%B5%D0%BD%D0%B8%D1%8F#.D0.9A.D0.B0.D0.BA_.D0.BF.D0.BE.D0.BB.D1.83.D1.87.D0.B8.D1.82.D1.8C_.D0.B3.D0.BE.D0.BB.D0.BE.D0.B2.D0.BD.D1.8B.D0.B5_.D1.83.D0.B1.D0.BE.D1.80.D1.8B

**Comment by AliEn-ST** [comment]
ahh okok, then i close the bug report, ty!
