### ISSUE TITLE
How to install sql database to mysql 5.5 or 6  7 ?

### ISSUE THREAD

**Issue by gskillact** [JoeAlisson/L2jOrg#264]
How to install sql database to mysql 5.5 or 6  7 ?
I have problem with new mysql (9+) for some program.
Thank you.

**Comment by vicochips** [comment]
Hello,

Actually I'm not sure you can install with mysql 5.5. The way you can try is to replace all UNSIGNED INT with INT

**Comment by JoeAlisson** [comment]
We use some features only available on MySQL 8. Thus we don't support older versions of MySQL.

**Comment by gskillact** [comment]
OMG....
MySQL 8. not support some feature of my program.... (Some important programs Active)
