### ISSUE TITLE
GEO not work?

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#265]
[INFO ][2020-05-31 20:47:27][GeoEnginePathFinding:<init>:35]: Loaded 7 path node buffers.
[INFO ][2020-05-31 20:47:27][GeoEngine:loadGeodataFiles:69]: Loaded 0 geodata files.
[WARN ][2020-05-31 20:47:27][GeoEngine:loadGeodataFiles:75]: Disabling  Path Finding.
[WARN ][2020-05-31 20:47:27][GeoEngine:loadGeodataFiles:79]: Forcing Sync Mode setting to Z_ONLY

config
# =================================================================
#                             Geodata
# =================================================================

# The Geodata files must be on geodata folder inside of Datapack root folder

# Because of real-time performance we are using geodata files only in
# diagonal L2D format now (using filename e.g. 22_16.l2d).
# L2D geodata can be obtained by conversion of existing L2J or L2OFF geodata.
# Launch "GeoDataConverter.bat/sh" and follow instructions to start the conversion.

# Player coordinates synchronization, default: SERVER
#   CLIENT - partial synchronization Client --> Server ; don't use it with geodata
#   SERVER - partial synchronization Server --> Client ; use this setting with geodata
#   Z_ONLY - Old system: will synchronize Z only
SyncMode = SERVER

# =================================================================
#                           Path finding
# =================================================================

# When line of movement check fails, the path finding algorithm is performed to look for
# an alternative path (e.g. walk around obstacle), default: true
EnablePathFinding = true

**Comment by expert43** [comment]
![image](https://user-images.githubusercontent.com/65304566/83359107-cbe2c800-a380-11ea-83a1-87eff92c3682.png)

**Comment by vicochips** [comment]
Hello, geodata must be on source folder, not data folder I think

**Comment by extysecz** [comment]
Yeah on source folder.

**Comment by vicochips** [comment]
What is the problem so ? :) because I use geodata and it works

**Comment by spiteridiick** [comment]
Me mande a geodata por favor

**Comment by doulu99** [comment]
geodata work .....copy your folder /gameserver/geodata to /gameserver

**Comment by JoeAlisson** [comment]
the geodata folder should be on datapack root, you can define it on server.properties
`DatapackRoot = .`
