### ISSUE TITLE
Not all RB on the map

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#266]
![image](https://user-images.githubusercontent.com/65304566/83359259-d2be0a80-a381-11ea-9e18-d314682a1c93.png)

These RB are not present and in fact, when the spawn RB is in this place, they are not added to the map. I didn't kill them)

**Comment by vicochips** [comment]
fix on vicochips branch, soon on develop

**Comment by vicochips** [comment]
fixed :)
