### ISSUE TITLE
Despot buffs

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#269]
Have Despot buffs work only in party - (without party even on themselves not lie down)

**Comment by vicochips** [comment]
Hello :) , what is despot buff ?

**Comment by vicochips** [comment]
Ok, I think it was dominator,

Fixed on vicochips branch, soon on develop

**Comment by Jo11y** [comment]
That's right, dominator! Buffs - meaning reinforcing skills!
