### ISSUE TITLE
The tyrant's totems are not placed on the autoroute

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#271]
The tyrant's totems are not placed on the autoroute

**Comment by vicochips** [comment]
Hello,

I just tried autoplay with totem and it works, 

TODO: 
Tyrant can have 2 active totems with different skill types at same time

    Puma Spirit Totem, Rabbit Spirit Totem, Wolf Spirit Totem - can't be applied at same time
    Ogre Spirit Totem, Bear Spirit Totem, Bison Spirit Totem - can't be applied at same time
        Ogre Spirit Totem + Puma Spirit Totem can be applied at same time

**Comment by vicochips** [comment]
Temporary fix with custom abnormal has been done
