### ISSUE TITLE
How to set passwort to sha1?

### ISSUE THREAD

**Issue by gskillact** [JoeAlisson/L2jOrg#272]
How to set passwort to sha1?

**Comment by JoeAlisson** [comment]
Why do you want change to an unsecure hashing  ?

**Comment by gskillact** [comment]
Donate program server using shi1 prove it not accept other code and can't change to other code. (Server provider)

**Comment by JoeAlisson** [comment]
Well I don't recommend to change it, butyou can change it here:
https://github.com/JoeAlisson/L2jOrg/blob/cf72b013ec1ecf63ca49952db063aacaee06841f/Commons/src/main/org.l2j.commons/org/l2j/commons/util/Util.java#L92

If this Donte program server is a 3rd-Party they can "figure out" all the passwords on your database.

**Comment by gskillact** [comment]
Thank you.
