### ISSUE TITLE
Missing NPC in giran

### ISSUE THREAD

**Issue by Hl4p3x** [JoeAlisson/L2jOrg#274]
![image](https://user-images.githubusercontent.com/17006168/83580753-d5983700-a50a-11ea-9c44-0d36ac5dcb6c.png)

**Comment by vicochips** [comment]
Hello, 

In what server is this pictures come from ?

Because on official there is no npc here. It is custom feature.

**Comment by extysecz** [comment]
> Hello,
> 
> In what server is this pictures come from ?
> 
> Because on official there is no npc here. It is custom feature.

Hey, on Official classic NCSoft there are these npcs.

**Comment by vicochips** [comment]
oh ok, I will add them so :)

**Comment by Hl4p3x** [comment]
> Hello,
> 
> In what server is this pictures come from ?
> 
> Because on official there is no npc here. It is custom feature.

Official NA server.  ;)

**Comment by vicochips** [comment]
done on vicochips, soon on develop
