### ISSUE TITLE
Rankers database...

### ISSUE THREAD

**Issue by Hl4p3x** [JoeAlisson/L2jOrg#276]
Why rankers sql have many errors when execute on my navicat?
![image](https://user-images.githubusercontent.com/17006168/83694356-dc37b480-a5c5-11ea-9d2b-b7084db19108.png)

[SQL] Query rankers start
[ERR] 4018 - No order list in window specification for 'rank'
[ERR] CREATE TABLE IF NOT EXISTS `rankers_snapshot`
(
    `id` INT UNSIGNED      NOT NULL DEFAULT 0,
    `exp`       BIGINT UNSIGNED           DEFAULT 0,
    `rank`      BIGINT UNSIGNED           DEFAULT 0,
    `rank_race` BIGINT UNSIGNED           DEFAULT 0,
    PRIMARY KEY (`id`),
    FOREIGN KEY FK_RANKERS_SNAPSHOT (`id`) REFERENCES characters (`charId`) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8MB4;

CREATE OR REPLACE VIEW rankers_race AS
    WITH ranked_race  AS (
        SELECT c.charId as id,
               c.char_name as name,
               c.exp,
               c.level,
               c.base_class as class,
               c.race,

               IFNULL((SELECT clan_name
                       FROM clan_data clan
                       WHERE clan.clan_id = c.clanid), ''
                   ) as clan_name,

               rank() over (
                   PARTITION BY c.race
                   ORDER BY c.exp desc
                   ) as `rank`,

               IFNULL(rs.`rank`, 0) as `rank_snapshot`,
               IFNULL(rs.rank_race, 0) as `rank_race_snapshot`

        from characters c LEFT JOIN rankers_snapshot rs on c.charId = rs.id
        where c.level >= 76
          AND c.accesslevel = 0
          AND (c.base_class BETWEEN 88 AND 118 OR c.base_class IN (131, 134, 195))
    )
    SELECT * FROM ranked_race WHERE `rank` <= 100;

CREATE VIEW rankers AS
SELECT c.charId as id,
       c.char_name as name,
       c.exp,
       c.level,
       c.base_class  as class,
       c.race,
       c.clanid  as clan_id,
       IFNULL((SELECT clan_name
                FROM clan_data clan
                WHERE clan.clan_id = c.clanid), ''
           ) as clan_name,

       rank() over (w)  as `rank`,

       (SELECT `rank`
        FROM rankers_race r
        WHERE r.id = c.charId
             )  as `rank_race`,

        IFNULL(rs.`rank`, 0) as `rank_snapshot`,
        IFNULL(rs.rank_race, 0) as `rank_race_snapshot`

from characters c LEFT JOIN rankers_snapshot rs on c.charId = rs.id
where c.level >= 76
  AND c.accesslevel = 0
  AND (c.base_class BETWEEN 88 AND 118 OR c.base_class IN (131, 134, 195))
    WINDOW w as (ORDER BY c.exp desc );

CREATE TABLE  IF NOT EXISTS `rankers_history`
(
    `id`   INT UNSIGNED NOT NULL,
    `exp`  BIGINT UNSIGNED DEFAULT 0,
    `rank` BIGINT UNSIGNED DEFAULT 0,
    `date` INT UNSIGNED,
    PRIMARY KEY (`id`, `date`)
) ENGINE = InnoDB
DEFAULT CHARSET = utf8MB4;
[SQL] Finished with error

**Comment by vicochips** [comment]
Hello :) 

Can u try : drop view rankers;

Then reinstall this table

**Comment by Hl4p3x** [comment]
> Hello :)
> 
> Can u try : drop view rankers;
> 
> Then reinstall this table

![image](https://user-images.githubusercontent.com/17006168/83780134-c32d1300-a65a-11ea-9764-fa1d98c8cc3e.png)

**Comment by vicochips** [comment]
ok :D
