### ISSUE TITLE
vicochipsdev-branch compiled 4.6.2020

### ISSUE THREAD

**Issue by extysecz** [JoeAlisson/L2jOrg#277]
Classmater does not work with popupwindow, you choose but after agree not will change.

classMaster classChangeEnabled="true" spawnClassMasters="false" showPopupWindow="true"

**Comment by extysecz** [comment]
![Shot00000](https://user-images.githubusercontent.com/23057968/83770389-4e210400-a681-11ea-9228-634cf0c92583.png)

![Shot00001](https://user-images.githubusercontent.com/23057968/83770414-524d2180-a681-11ea-8a06-aa4a5f9bd75e.png)

**Comment by extysecz** [comment]
Every race and class.

**Comment by vicochips** [comment]
fk it was working.. they must have change the packet again

**Comment by extysecz** [comment]
Yeah I know, I tried it two days ago and it worked.

**Comment by vicochips** [comment]
Fixed on vicochips branch :)
