### ISSUE TITLE
Augment bug

### ISSUE THREAD

**Issue by Hl4p3x** [JoeAlisson/L2jOrg#282]
When you try augment, the window close and nothing happened...
No log in GS, no MSG in game..

![image](https://user-images.githubusercontent.com/17006168/83818454-6864dd00-a695-11ea-81c6-05cf089a3c8d.png)

**Comment by vicochips** [comment]
Life stone in kamael classic are: 

Low-grade Life Stone
Mid-grade Life Stone
High-grade Life Stone

There is no Top grade life stone.

**Comment by vicochips** [comment]
https://translate.google.com/translate?hl=fr&sl=auto&tl=en&u=https%3A%2F%2Fl2central.info%2Fclassic%2F%25D0%2597%25D0%25B0%25D1%2587%25D0%25B0%25D1%2580%25D0%25BE%25D0%25B2%25D0%25B0%25D0%25BD%25D0%25B8%25D0%25B5_%25D0%25BF%25D1%2580%25D0%25B5%25D0%25B4%25D0%25BC%25D0%25B5%25D1%2582%25D0%25BE%25D0%25B2

**Comment by Hl4p3x** [comment]
Invalid! Thank you. ;)
