### ISSUE TITLE
Just a question about geodata files.

### ISSUE THREAD

**Issue by Hl4p3x** [JoeAlisson/L2jOrg#283]
Which geodata we use on l2org project?
Anyone have a link to download?

Thank you all!

**Comment by vicochips** [comment]
you can use this one :) 

https://www.mediafire.com/file/fzw7fplavow88wb/L2J_Mobius_Classic_3.0_TheKamael_Geodata.zip

**Comment by Hl4p3x** [comment]
Thank you so much, vicochips. You rock!
