### ISSUE TITLE
Some items to fix

### ISSUE THREAD

**Issue by extysecz** [JoeAlisson/L2jOrg#287]
- [x] Chefs Fish Stew - Victory
- [x] Shining Scroll of Mood Melody
- [x] Mark of journey 1,2,3 not benefic passive skills
- [x] SP Scroll 2000SP
- [x] Eva’s talisman number of icon diffwrent from skill passive level
- [x] Advanced Scroll of Escape Event

**Comment by vicochips** [comment]
Will look at it tomorrow :)
