### ISSUE TITLE
Luxury Shop

### ISSUE THREAD

**Issue by extysecz** [JoeAlisson/L2jOrg#294]
![image](https://user-images.githubusercontent.com/23057968/84011552-95a3da80-a976-11ea-8d73-aa9f827931b7.png)

![image](https://user-images.githubusercontent.com/23057968/84011583-a0f70600-a976-11ea-9fca-2b3eb57caa39.png)
https://l2wiki.com/classic/Luxury_Shop

**Comment by MaJr-Dp** [comment]
Fix
The wrong link in the file was
