### ISSUE TITLE
Forest of Mirros - call of the spirits - harit

### ISSUE THREAD

**Issue by extysecz** [JoeAlisson/L2jOrg#300]
![image](https://user-images.githubusercontent.com/23057968/84044168-7d987f00-a9a7-11ea-9856-8404a8af1b9a.png)

![image](https://user-images.githubusercontent.com/23057968/84044178-825d3300-a9a7-11ea-8e08-bde706d71a9a.png)

It is monster , not npc.

**Comment by vicochips** [comment]
fixed
