### ISSUE TITLE
summon Life cubic not work (lvl 74)

### ISSUE THREAD

**Issue by extysecz** [JoeAlisson/L2jOrg#316]
![image](https://user-images.githubusercontent.com/23057968/84315704-5ccc5700-ab6a-11ea-938d-224338a6f991.png)
![image](https://user-images.githubusercontent.com/23057968/84315782-740b4480-ab6a-11ea-8ea1-3928740a2546.png)

**Comment by vicochips** [comment]
Fixed on vicochips soon on develop
