### ISSUE TITLE
Clan skills 

### ISSUE THREAD

**Issue by extysecz** [JoeAlisson/L2jOrg#320]
Clan leader passive skills:
![image](https://user-images.githubusercontent.com/23057968/84382791-7661b300-abeb-11ea-9a8f-507e6fecfbbe.png)

Clan member passive skills:
![image](https://user-images.githubusercontent.com/23057968/84382854-91ccbe00-abeb-11ea-93ee-ad306eec1d05.png)

relog,server restart = same like image

**Comment by JoeAlisson** [comment]
See #199
