### ISSUE TITLE
After leave clan title will remain

### ISSUE THREAD

**Issue by extysecz** [JoeAlisson/L2jOrg#322]
![image](https://user-images.githubusercontent.com/23057968/84405888-0d893380-ac09-11ea-972d-c20543ddca2d.png)

Clan skill remain
![image](https://user-images.githubusercontent.com/23057968/84406461-db2c0600-ac09-11ea-9b30-94c29c7a9af7.png)

**Comment by vicochips** [comment]
and if you restart?

**Comment by extysecz** [comment]
yeah :)

**Comment by MaJr-Dp** [comment]
Was the treasure system updated to the latest update?
