### ISSUE TITLE
some items to fix (talismans) (passive skills)

### ISSUE THREAD

**Issue by extysecz** [JoeAlisson/L2jOrg#323]
![image](https://user-images.githubusercontent.com/23057968/84412518-a753df00-ac0f-11ea-97d9-1ba9e504dd6a.png)
![image](https://user-images.githubusercontent.com/23057968/84412539-afac1a00-ac0f-11ea-8005-28e5360c587a.png)
![image](https://user-images.githubusercontent.com/23057968/84412556-b76bbe80-ac0f-11ea-9d32-f1a8955a12c0.png)
![image](https://user-images.githubusercontent.com/23057968/84412929-3c56d800-ac10-11ea-866a-5f84ef95d081.png)

**Comment by vicochips** [comment]
https://lineage2.plaync.com/board/l2guide/view?articleId=24&page=2&categoryId=0&viewMode=thumb&size=20

Here is the list of talisman, dimensional is not anymore on server 🗡️ 

I have done all, I just need to do venir's

**Comment by extysecz** [comment]
ok nice :)

**Comment by MaJr-Dp** [comment]
It’s better to do all the talismans - because how: Events, new items in the L shop and the like introduce each update.
I am less than possible - I am correcting these talismans.
