### ISSUE TITLE
Some skills not working cannot be used

### ISSUE THREAD

**Issue by extysecz** [JoeAlisson/L2jOrg#324]
![image](https://user-images.githubusercontent.com/23057968/84414992-6c9f7600-ac12-11ea-8a91-fcd28aca9d58.png)
![image](https://user-images.githubusercontent.com/23057968/84415167-a83a4000-ac12-11ea-9060-5581b9b18eab.png)

![image](https://user-images.githubusercontent.com/23057968/84419176-8479f880-ac18-11ea-8915-d20830fe7cd0.png)
![image](https://user-images.githubusercontent.com/23057968/84419185-880d7f80-ac18-11ea-887e-8ff1825bdc18.png)

**Comment by vicochips** [comment]
With what weapon did u try?

**Comment by extysecz** [comment]
Ancient,two handed.

**Comment by vicochips** [comment]
fixed :)
