### ISSUE TITLE
Pona NPC

### ISSUE THREAD

**Issue by extysecz** [JoeAlisson/L2jOrg#325]
add to pona exchange jewel stones and: 
Transformation Extract Scroll
![image](https://user-images.githubusercontent.com/23057968/84416317-55618800-ac14-11ea-9db8-26eac3e98b37.png)

**Comment by vicochips** [comment]
On official pona doesnt sell that

**Comment by extysecz** [comment]
hmm then where can get it ?

**Comment by vicochips** [comment]
I don't know :D

**Comment by MaJr-Dp** [comment]
I will make it clear - all the sellers of Giran - have been fixed
