### ISSUE TITLE
skills tyrant 

### ISSUE THREAD

**Issue by extysecz** [JoeAlisson/L2jOrg#328]
unactive after 1 second...
![image](https://user-images.githubusercontent.com/23057968/84503955-6ca78080-acbb-11ea-90c7-080412908306.png)

can't have two totems ogre+puma
![image](https://user-images.githubusercontent.com/23057968/84509770-797ca200-acc4-11ea-8c03-ca6a10fbab6e.png)

**Comment by vicochips** [comment]
fury fist fixed
