### ISSUE TITLE
IDE Debugging

### ISSUE THREAD

**Issue by excellence97** [JoeAlisson/L2jOrg#333]
Hello!
I'm trying to get this project to compile/debug through Intellj, right now It's running without gradle.
Initially I was thinking that maybe the issue was a compiler flag or something but I'm not sure because the exact same thing happens when AuthServer gradle run is used as a launch configuration.

This is what happens when I'm trying to log in
![image](https://user-images.githubusercontent.com/10416049/84669844-3005a000-aeda-11ea-8ab0-827c7fe50a28.png)

GameServer is experiencing database issues as well, how do you guys debug through your IDE? Any chance you could share some launch configurations? 

java --enable-preview -Dfile.encoding=UTF-8 -Xmx256m --add-exports java.base/jdk.internal.misc=io.github.joealisson.primitive -p "loadsofjarshere" -m org.l2j.authserver/org.l2j.authserver.AuthServer
Here's how intellj currently launches the thing.

Here's my compiler flags as well 
![image](https://user-images.githubusercontent.com/10416049/84670211-adc9ab80-aeda-11ea-9dcd-eaa6510a6095.png)

I have zero experience with gradle and different modules in general, I'm trying to simplify the compile/run process so I can hotswap changes and work on the assembly without having to "distribute" and run through .bat every time.

**Comment by vicochips** [comment]
Hello :) if u want to come on discord I will be able to help u faster tonight :) !

https://github.com/JoeAlisson/L2jOrg/issues/290

**Comment by excellence97** [comment]
Is there an invite link? 

> 
> 
> Hello :) if u want to come on discord I will be able to help u faster tonight :) !
> 
> #290

Is there an invite link?

**Comment by vicochips** [comment]
I send u the issue with the link in previous post :)
