### ISSUE TITLE
visual errors with summoners (exps)

### ISSUE THREAD

**Issue by extysecz** [JoeAlisson/L2jOrg#349]
![image](https://user-images.githubusercontent.com/23057968/85458431-63fb5800-b5a1-11ea-8e34-343cb6423759.png)
![image](https://user-images.githubusercontent.com/23057968/85458445-68c00c00-b5a1-11ea-80aa-3811ea46f76e.png)
![image](https://user-images.githubusercontent.com/23057968/85458462-6f4e8380-b5a1-11ea-9440-7fbdce921723.png)

**Comment by vicochips** [comment]
I think it is solved

To be confirmed
