### ISSUE TITLE
rb jewels

### ISSUE THREAD

**Issue by extysecz** [JoeAlisson/L2jOrg#350]
CORE LVL 1 PASSIVE SKILL MISSING
ALL BAIUM RINGS BAD PASSIVE SKILLS

**Comment by MaJr-Dp** [comment]
I fixed all passive skills of epic jewelry
Where the fix went - look for pools))

**Comment by MaJr-Dp** [comment]
Done
https://github.com/JoeAlisson/L2jOrg/commit/5255b72c41bd4e37d95448274f3b82c2c4287554
