### ISSUE TITLE
attack distance\Saint Spear\geodata

### ISSUE THREAD

**Issue by Kinasai** [JoeAlisson/L2jOrg#354]
I put on my bow(draconic), then I put on my spear(SS)
save range for spear from bow
![image](https://user-images.githubusercontent.com/67678968/86213453-28f5b780-bb93-11ea-8d6c-50fe326efe35.png)
![image](https://user-images.githubusercontent.com/67678968/86485207-8f383100-bd71-11ea-8b45-c02d8f80835e.png)
_**a bug because of the skill id 113, if used without it, there will not be a +400 radius when swapping from a bow to another weapon**_
Saint Spear no damage to close targets
geodata read ./geodata not from ./data/geodata

**Comment by vicochips** [comment]
I think it is related to geodata, that is not really done in this area

**Comment by Kinasai** [comment]
experimented and if you do not change the weapon from the bow to the pole, and remove the bow and then put on the pole will work fine. geodata works
