### ISSUE TITLE
You can't buy daily items with adena on L2 Coin Shop..

### ISSUE THREAD

**Issue by theAbbys** [JoeAlisson/L2jOrg#355]
You can't buy items with adena like official data..
You buy a X items per day with adena..

Oficial NA
![image](https://user-images.githubusercontent.com/67714367/86294870-65d9a280-bbc3-11ea-8f2e-fdbe75e8099e.png)

L2jOrg
![image](https://user-images.githubusercontent.com/67714367/86294915-7b4ecc80-bbc3-11ea-98b6-f15eef202994.png)

**Comment by bahamus20** [comment]
How to fix?

**Comment by JoeAlisson** [comment]
The L2 Coin is not fully implemented yet

see #108
