### ISSUE TITLE
L2 Store free and daily items..

### ISSUE THREAD

**Issue by theAbbys** [JoeAlisson/L2jOrg#356]
On off NA you can obtain daily items from l2store and u can purchase once a day..

L2Off NA
![image](https://user-images.githubusercontent.com/67714367/86295342-5eff5f80-bbc4-11ea-9cae-5ea72c3e4737.png)

L2ORG
![image](https://user-images.githubusercontent.com/67714367/86295361-6aeb2180-bbc4-11ea-8914-ef0dea5b99f2.png)

**Comment by bahamus20** [comment]
omg

**Comment by bahamus20** [comment]
How to fix?

**Comment by JoeAlisson** [comment]
just need to put the attribute restrictionDay on product in primeShop.xml

**Comment by JoeAlisson** [comment]
This will be addressed on #204
