### ISSUE TITLE
l2store don't give Vip Points

### ISSUE THREAD

**Issue by l2kannon** [JoeAlisson/L2jOrg#362]
when i buy items in l2 store we expect gain vip points. but nothing happens
also you can buy 12333 items for 1 L2 Coins no matter how much you buy always spend the value of 1 item

**Comment by JoeAlisson** [comment]
The VIP points is working fine:

![Screenshot from 2020-07-22 11-49-12](https://user-images.githubusercontent.com/5034192/88191363-bf0c8300-cc11-11ea-8dce-a5140458b222.png)

After buy something on L2Store:

![Screenshot from 2020-07-22 11-49-44](https://user-images.githubusercontent.com/5034192/88191443-d2b7e980-cc11-11ea-854b-a77c75d386f1.png)

About the L2 Coin Store see #108
