### ISSUE TITLE
How to change VIP L2 Coine to other items?

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#369]
How to change VIP L2 Coine to other items?

Thank

**Comment by JoeAlisson** [comment]
I'm not sure which coin you are talking about, is it the coin used on L2Store or the dropped coins to VIP Players ?

**Comment by bahamus20** [comment]
VIP To register

**Comment by bahamus20** [comment]
![image](https://user-images.githubusercontent.com/63811728/89610495-db145380-d8a4-11ea-9efc-0759cf9a2ff2.png)

**Comment by JoeAlisson** [comment]
This system is not ready yet.
