### ISSUE TITLE
L2 Coin Shop (L Shop)

### ISSUE THREAD

**Issue by Forcecat01** [JoeAlisson/L2jOrg#372]
hello, there is such a problem,

I have 10 L coin, just buy 10 Talisman Aden 

![Screenshot_1](https://user-images.githubusercontent.com/54755997/89468820-ef5f3000-d780-11ea-9499-4a38b7658564.png)

and get +10 L coin and 10 Box Talisman Aden

![Screenshot_2](https://user-images.githubusercontent.com/54755997/89468903-1b7ab100-d781-11ea-813f-6e7aac6bf8f7.png)

in another version, you could buy an unlimited number of items for 1 L Coin, now I get L Coin for buying, how to deal with this problem?

Sale for "Adena" and sale per day does not work. Thanks

![Screenshot_3](https://user-images.githubusercontent.com/54755997/89469140-81ffcf00-d781-11ea-8f3a-1e5d6e75749a.png)

**Comment by JoeAlisson** [comment]
See #108

**Comment by vicochips** [comment]
Hello, do u use the « release «  or the source ?

**Comment by Forcecat01** [comment]
> Hello, do u use the « release «  or the source ?

1.7 and this fix is ​​not there
