### ISSUE TITLE
Enchantment chance for accessories (talisman, pendants...)

### ISSUE THREAD

**Issue by vicochips** [JoeAlisson/L2jOrg#387]
https://4gameforum.com/threads/780149/

Some talismans, bracelets etc doesnt not have  the right enchancement chance

**Comment by Psixxo** [comment]
Please create config for enchant. Where write chanse for weapon/Armor/Agathios/Pendants/Talismans Eva/Aden/Speed etc

**Comment by vicochips** [comment]
All config are in Enchancement.xml in datapack.

We have updated it :)
