### ISSUE TITLE
Lorenzo (soellbook trader)

### ISSUE THREAD

**Issue by extysecz** [JoeAlisson/L2jOrg#389]
![image](https://user-images.githubusercontent.com/23057968/90239158-62bf0c80-de27-11ea-9093-eebcd7874133.png)
![image](https://user-images.githubusercontent.com/23057968/90239172-68b4ed80-de27-11ea-8f4d-3b41b4057bbf.png)

**Comment by Hl4p3x** [comment]
`@ -2,6 +2,7 @@
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/buylist.xsd">
	<npcs>
		<npc>30254</npc> 
		<npc>30840</npc> 
	</npcs>
	<item id="1378" price="20259" /> 
	<item id="1384" price="39134" /> `

**Comment by vicochips** [comment]
fixed
