### ISSUE TITLE
Invisible spider in talkin island

### ISSUE THREAD

**Issue by hozuke** [JoeAlisson/L2jOrg#391]
**Describe the bug**

Invisible spiders in Talkin Island, when you do the lvl 15 quest it sends you to the north of Talkin to hunt 15 spiders, but there are many that are invisible, when you target it, it shows the name and they also appear on the radar, but when you hit them, you do it on the air and without effects .. and die from a single attack.

**To Reproduce**
take the quest level 15

**Comment by extysecz** [comment]
Geodata on?

**Comment by hozuke** [comment]
yes and set correctly

**Comment by bahamus20** [comment]
Geodata !!

**Comment by vicochips** [comment]
fixed on next release :)
