### ISSUE TITLE
Blue Gemstone

### ISSUE THREAD

**Issue by hozuke** [JoeAlisson/L2jOrg#392]
blue gemstone, without talking to the first npc. I have created two characters to verify and both characters got the blue genstone without talking to the corresponding npc. you just have to kill a couple of gremblins and talk to the npc and you get the soulshos.

**Comment by MaJr-Dp** [comment]
What race?

**Comment by hozuke** [comment]
> What race?

Human

**Comment by MaJr-Dp** [comment]
In the evening I will check all the races (there was no such problem)

**Comment by MaJr-Dp** [comment]
Failed to reproduce the bug.
Everything works according to - off (await update)
