### ISSUE TITLE
Can't attack monster.

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#394]
![image](https://user-images.githubusercontent.com/63811728/90713641-fd0fcc00-e2cf-11ea-9ca7-a2ef6ba45eef.png)

**Comment by bahamus20** [comment]
![image](https://user-images.githubusercontent.com/63811728/90713700-1e70b800-e2d0-11ea-8c8c-2908b838507f.png)

**Comment by extysecz** [comment]
Geodata on?

**Comment by vicochips** [comment]
Can u give us the log of your gameserver when u launch it? Because all your problem seems that  geodata is OFF
