### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#395]
![image](https://user-images.githubusercontent.com/63811728/90716080-4236fc80-e2d6-11ea-91ca-6a43dce74062.png)

**Comment by MaJr-Dp** [comment]
GS message?

**Comment by bahamus20** [comment]
> GS message?

GS no any error

**Comment by JoeAlisson** [comment]
Client side bug, this message is not sended by server.
![Screenshot from 2020-08-30 16-18-31](https://user-images.githubusercontent.com/5034192/91667674-b2b2fa00-eadc-11ea-91c7-8f833701a5ef.png)
