### ISSUE TITLE
Help eclipse error.

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#398]
eclipse-java-2020-03-R-Java14-win32-x86_64
java jdk-14.0.1
windows 10 64 bit

![image](https://user-images.githubusercontent.com/63811728/90862597-db8a0f80-e3b7-11ea-84ae-44f666b848ba.png)

Thank

**Comment by bahamus20** [comment]
![image](https://user-images.githubusercontent.com/63811728/90862805-30c62100-e3b8-11ea-953d-897e1f494a75.png)

**Comment by vicochips** [comment]
are u on our discord ?

**Comment by extysecz** [comment]
Bahamus, I recommend you join the discord for better communication.

**Comment by JoeAlisson** [comment]
Re-import your project through gradle
