### ISSUE TITLE
Error player level 23 dark mage login.

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#399]
[INFO ][2020-08-21 18:26:38][accounting:runImpl:137]: [Player: AAAAAA[39688] - Account: ggggg - IP: 171.97.74.14] Logged in
[WARN ][2020-08-21 18:26:40][ClientPacketHandler:makePacketWithFactory:68]: Client [Player: THISISADOG[39688] - Account: ggggg - IP: 171.97.74.14] sent packet ACQUIRE_SKILL_INFO at invalid state JOINING_GAME Required States: [IN_GAME] -
[73]: 00000000 73360400000100000000000000       s6...........

**Comment by JoeAlisson** [comment]
This is not a error, just a warn send a packet on a Invalid state, it can be caused by network latency. You don't need to worry about it unless you notice something wrong with player's skill
