### ISSUE TITLE
Need AI for Lord Ishka

### ISSUE THREAD

**Issue by MaJr-Dp** [JoeAlisson/L2jOrg#402]
It is necessary to implement AI for Lord Ishka (no longer RB)
It wanders throughout the Far East, has the logic as in the video.
After murder - adjusts a buff on his "Assassins" (buff is eased)
Dialogue on Spawn and Kill (video)

https://youtu.be/BoreD-jZrwc?t=350

**Comment by vicochips** [comment]
the character will receive a positive effect: P. / M. Atk. +100, P. Crete. Atk. and the Power of Mag. Crete. Atk. + 1% for 20 minutes.

**Comment by vicochips** [comment]
I have done it, to test
