### ISSUE TITLE
create race rank transforms for 1-3 place

### ISSUE THREAD

**Issue by Psixxo** [JoeAlisson/L2jOrg#409]
On classic kamael part 4 have a race transform for 1-3 place in system ranks. 
Transform name Worthy Warrior Form
https://l2central.info/essence/%D0%A0%D0%B0%D0%BD%D0%B3%D0%B8_%D0%B8_%D0%BD%D0%B0%D0%B3%D1%80%D0%B0%D0%B4%D1%8B

on l2central clssic i did not find this information. 

But in the classic kamael part4 it is the same as in essence.

**Comment by vicochips** [comment]
Done :)

Just need the kamael one :)
