### ISSUE TITLE
Information is not updated - summons stat windows

### ISSUE THREAD

**Issue by MaJr-Dp** [JoeAlisson/L2jOrg#411]
Information is not updated - summons stat windows
Before buff
![image](https://user-images.githubusercontent.com/13205658/92312736-65e38d80-efcc-11ea-8bb4-4242987c7bdf.png)

After the buff
![image](https://user-images.githubusercontent.com/13205658/92312756-91ff0e80-efcc-11ea-9237-5f74662c83f7.png)

**Comment by JoeAlisson** [comment]
Fixed in #432
