### ISSUE TITLE
Problems with displaying HP

### ISSUE THREAD

**Issue by MaJr-Dp** [JoeAlisson/L2jOrg#413]
When I or Summon - uses a skill like "Sacrifice" = 69 or "Shaide Sacrifice" = 4707
There is such a bug (look at the photo - on the HP)
![image](https://user-images.githubusercontent.com/13205658/92326139-93761880-f058-11ea-8e5e-c6ce04549eb3.png)

![image](https://user-images.githubusercontent.com/13205658/92326146-9ec94400-f058-11ea-8af9-d30d366a596e.png)

Player:
![image](https://user-images.githubusercontent.com/13205658/92326164-c3bdb700-f058-11ea-8584-ce82b1b49a2b.png)

**Comment by JoeAlisson** [comment]
related #411

**Comment by JoeAlisson** [comment]
Is this still happens ? I couldn't reproduce. 

If yes, can you tell me detailed how to reproduce it ?

**Comment by MaJr-Dp** [comment]
Closed.
Fix (forgot to close)
