### ISSUE TITLE
Summon and pet problem

### ISSUE THREAD

**Issue by creative87rus** [JoeAlisson/L2jOrg#419]
If you press attack and after the stop button, the pet deals damage every time you press attack

**Comment by vicochips** [comment]
Hello,

I don't understand the error,

I try to attack with pet ok, I press stop ok, and I press attack again ok

**Comment by creative87rus** [comment]
Try fast click attack and stop.Press without stopping 5-6 sec. And last click attack.And you will see that Sammon starts hitting very quickly
