### ISSUE TITLE
Problems Rapires/Ancient Swords

### ISSUE THREAD

**Issue by MaJr-Dp** [JoeAlisson/L2jOrg#420]
![image](https://user-images.githubusercontent.com/13205658/92517405-442e1480-f21f-11ea-8978-a7b0807cf0ff.png)

Rapiers and Ancient Swords cannot carry:

Rapiers cannot carry: Orcs and Dwarves.

Ancient swords cannot be worn by: Humans, Elves, Dark Elves.

This must be done in the kernel (you can display the config)

**Comment by vicochips** [comment]
Done
