### ISSUE TITLE
How to change password to SHA type?

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#422]
How to change password to SHA type?

**Comment by bahamus20** [comment]
L2jOrg/Commons/src/main/org.l2j.commons/org/l2j/commons/util/Util.java 

MessageDigest md = MessageDigest.getInstance("SHA3-256");
to
MessageDigest md = MessageDigest.getInstance("SHA1");

**Comment by bahamus20** [comment]
or make to config file.

**Comment by JoeAlisson** [comment]
It's not recommended to use such old digest algorithm since it is not secure.

**Comment by bahamus20** [comment]
ok thank
