### ISSUE TITLE
Rank system 

### ISSUE THREAD

**Issue by Forcecat01** [JoeAlisson/L2jOrg#424]
Hi, the rank system is not working correctly. 

how does it work now: 
Each race has its own top 3 rankings on the server.

![Screenshot_1](https://user-images.githubusercontent.com/54755997/93093617-90f36e80-f6a9-11ea-9810-d79f146947cb.png)

It should be:
All races must be in 1 list and have top 3 (different classes) in terms of the amount of experience gained.

![699px-Система_рангов_-_окно](https://user-images.githubusercontent.com/54755997/93093738-b4b6b480-f6a9-11ea-8bb3-f4d65284daf4.jpg)

**Comment by Forcecat01** [comment]
and also such a moment, the rating now starts from level 76 with 3 professions. but should from 2nd profession level 40

**Comment by JoeAlisson** [comment]
I don't have this problem, check you rankers_snapshot table.

![Screenshot from 2020-09-14 11-24-11](https://user-images.githubusercontent.com/5034192/93098258-0a289c80-f67d-11ea-8e73-15531dd6ae0e.png)

About the ranking conditions been at level 76 is based on NA server.

https://www.lineage2.com/news/shadow-of-the-kamael-update-preview

**Comment by Forcecat01** [comment]
There are no questions about the level.

bonuses and entries will appear after 6:30
![Screenshot_1](https://user-images.githubusercontent.com/54755997/93099459-b33cba80-f6b0-11ea-8ec0-b75cf687f3e7.png)

![Screenshot_2](https://user-images.githubusercontent.com/54755997/93099703-feef6400-f6b0-11ea-99aa-8644a10fbeb7.png)

but already now I see that all races have their own top 3 ratings on the server.

I'll see after 6:30 what will change

**Comment by Forcecat01** [comment]
> I don't have this problem, check you rankers_snapshot table.
> 
> ![Screenshot from 2020-09-14 11-24-11](https://user-images.githubusercontent.com/5034192/93098258-0a289c80-f67d-11ea-8e73-15531dd6ae0e.png)
> 
> About the ranking conditions been at level 76 is based on NA server.
> 
> https://www.lineage2.com/news/shadow-of-the-kamael-update-preview

Create please 2 more level 86 orcs for yourself and check how they get to the top

**Comment by JoeAlisson** [comment]
With 2 more level 86  orcs still working

![Screenshot from 2020-09-14 12-52-08](https://user-images.githubusercontent.com/5034192/93108506-3fd38280-f689-11ea-93cb-129daefffff9.png)

**Comment by Forcecat01** [comment]
> With 2 more level 86 orcs still working
> 
> ![Screenshot from 2020-09-14 12-52-08](https://user-images.githubusercontent.com/5034192/93108506-3fd38280-f689-11ea-93cb-129daefffff9.png)

I probably understood what my problem is. thank you for the test
