### ISSUE TITLE
PK Debuff System

### ISSUE THREAD

**Issue by Forcecat01** [JoeAlisson/L2jOrg#425]
Is it possible to add this system? very useful how the system turned out

![Screenshot_2](https://user-images.githubusercontent.com/54755997/93104557-ae7b0500-f6b6-11ea-9b97-3067050e3602.png)

**Comment by Forcecat01** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/54755997/93105523-db7be780-f6b7-11ea-9dd9-f03a6ff40a9f.png)

**Comment by JoeAlisson** [comment]
see #156
