### ISSUE TITLE
Summons  does need resummon to refresh all buffs 

### ISSUE THREAD

**Issue by nswnazuka** [JoeAlisson/L2jOrg#432]
Needs to resummon pet to make buffs reload on it

**Comment by MaJr-Dp** [comment]
The problem is not in Skills - but in PackageInfoNPC
Make a teleport to another place - and then the summon's stats will be updated

**Comment by nswnazuka** [comment]
the real problem isnt skill
it is that the summon needs to be resummoned to refresh buff status
even with standard buffs (might ect)
