### ISSUE TITLE
Vampiric Attack 

### ISSUE THREAD

**Issue by l2kannon** [JoeAlisson/L2jOrg#441]
**Describe the bug**
Abnormal type VAMPIRIC_ATTACK doesnt affect magical and ranged damage only melee

i talk with experience players that play offi for years, and they told me that, vampiric rage (ID: 1268) and vampiric dance (ID: 310) affect magic and ranged attacks

**Comment by Psixxo** [comment]
mele damage, range damage and mage damage have a vampiric, if have buff "vampiric rage" or "Chant of Vampire" and "Dance of the Vampire". But with the chance indicated in these buffs.

**Comment by vicochips** [comment]
Yeah it is the case here too , there is a bug ?

**Comment by MaJr-Dp** [comment]
The skill works fine.
What is the problem?

**Comment by l2kannon** [comment]
the skill works fine for physical atacks, with ranged and magical doesnt work...

**Comment by MaJr-Dp** [comment]
checked many times - does not work on magician skills and ranged attacks

**Comment by MaJr-Dp** [comment]
checked many times - does not work on magician skills and ranged attacks

**Comment by vicochips** [comment]
Fixed next release
