### ISSUE TITLE
Error Console problem freeze 

### ISSUE THREAD

**Issue by ryclos** [JoeAlisson/L2jOrg#443]
**Describe the bug**
When a character to connect in the server i have often this error on the console gameserver (**Screenshots**) the character have a freeze probleme with no load the spawn, items in the game, inventory, skills etc etc

**Screenshots**
![image](https://user-images.githubusercontent.com/9601851/96325049-8f76d800-0fc0-11eb-8a6e-7b5e04a712bb.png)

**Desktop (please complete the following information):**
 - OS: Linux Debian 9 (Stretch)

**Additional context**
A friend tell me this is a Windows OS problem... But i'm under Linux..

Thank you

**Comment by JoeAlisson** [comment]
Fixed in  JoeAlisson/async-mmocore@7eb1aac3d528154f807bacdad385fc827f7ec8fb
