### ISSUE TITLE
Duplicated Items

### ISSUE THREAD

**Issue by l2kannon** [JoeAlisson/L2jOrg#445]
**Describe the bug**
when any char acquired any item in game and instead he consume, sell, or drop make a relog, those items appears again in the inventory.
Also i installed 4 times the database from 0 and happen the same

**To Reproduce**

1. Buy any scroll for buff
2. Consume 
3. Relog the char

I have all programs updated to the latest version, Its not problem of old version programs

using

Mysql 8.0.21
Java 15

**Comment by MaJr-Dp** [comment]
On the Manax server, it turned out to reproduce the "duplication of items" - on another test server: it did not work out to reproduce, perhaps a problem with the tables ...
Check someone else
