### ISSUE TITLE
type* FriendlyMob 

### ISSUE THREAD

**Issue by Forcecat01** [JoeAlisson/L2jOrg#456]
there are mobs-type monsters in the initial locations, * if you are attacked by an aggressive monster, they will help you * (also kills people with karma)

We now have such monsters with the FriendlyMob type, when autohunting, they hit the target 

![Screenshot_1](https://user-images.githubusercontent.com/54755997/96964019-5f748b00-1512-11eb-9ea4-c93cc177fc34.png)

**Comment by JoeAlisson** [comment]
Sorry, I didn't understand what is the problem. Can you explain it ?
