### ISSUE TITLE
Game issue multisell

### ISSUE THREAD

**Issue by nswnazuka** [JoeAlisson/L2jOrg#458]
If you make a multisell that requires 2 ingredients items to get one,
if you have 1 item above the 2 required, says you need 1 more item - but still consumes the other item 
so you lose your item for no reason

**Comment by JoeAlisson** [comment]
Can you give me a exemple of multisell or npc that have this issue ?

I couldn't reproduce it:

![Screenshot from 2020-10-24 09-09-42](https://user-images.githubusercontent.com/5034192/97081450-e8ee9080-15d8-11eb-9910-5fe59866247b.png)

**Comment by nswnazuka** [comment]
my custom ones, also not with this kind of multisell but the other one, with chances written on

**Comment by MaJr-Dp** [comment]
Show an example of your file
