### ISSUE TITLE
PVP all the time

### ISSUE THREAD

**Issue by l2kannon** [JoeAlisson/L2jOrg#459]
**Describe the bug**
The config :

# Peace Zone Modes:
# 0 = Peace All the Time
# 1 = PVP During Siege for siege participants
# 2 = PVP All the Time
# Default: 0
PeaceZoneMode = 0

doesnt affect at all, outside any city a player can attack another player without use of CTRL key pressed

**Comment by JoeAlisson** [comment]
This config is working fine, if it is activate you can attack players inside peace zones.

![Screenshot from 2020-10-24 09-38-14](https://user-images.githubusercontent.com/5034192/97082047-189f9780-15dd-11eb-8382-118971f270be.png)

**Comment by l2kannon** [comment]
i have deactivated... and outside cities i can atack players without press ctrl... thats what i mean

**Comment by l2kannon** [comment]
outside city... normally a player to make pvp need to press ctrl...

**Comment by JoeAlisson** [comment]
Any specific skill ?

**Comment by l2kannon** [comment]
normal attack... and all skills

**Comment by JoeAlisson** [comment]
I tried In some locations, it is working fine.

Make sure your client is not on combat mode and if you still attack without ctrl, please tell me the exact location where this is happening.
