### ISSUE TITLE
auto farm 

### ISSUE THREAD

**Issue by inparad1se** [JoeAlisson/L2jOrg#462]
https://www.youtube.com/watch?v=TWvsFX0tO14&feature=youtu.be

does not work stably auto farm 
if you turn it on auto farm before using skills , auto farm work .. but if u use skill on auto farm mode , player stop target mobs and use skills . But when you press that the player would run somewhere auto farm starts work

**Comment by vicochips** [comment]
right !

Auto farm is not really complete for now, it is a hard thing to do :D

**Comment by Bru7aLMike** [comment]
This issue has been addressed and fixed in the latest iteration of the auto hunt engine.
