### ISSUE TITLE
Error in the console and crash client

### ISSUE THREAD

**Issue by ryclos** [JoeAlisson/L2jOrg#463]
**Describe the bug**
Console errors appear and cause players to crash. As long as the server has not been restarted or shut down, the server is stuck!
Players say that this would surely be related to toggle skills in autofarm or items.

**Screenshots**
[message.txt](https://github.com/JoeAlisson/L2jOrg/files/5460750/message.txt)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version : Debian 9 stretch

**Comment by JoeAlisson** [comment]
Fixed at JoeAlisson/async-mmocore@7eb1aac3d528154f807bacdad385fc827f7ec8fb
