### ISSUE TITLE
Lvl 90 to Lvl 1 When you die and click "to village"

### ISSUE THREAD

**Issue by ryclos** [JoeAlisson/L2jOrg#465]
**Describe the bug**
A character lvl 90 dies and get back to lvl 1 without any skills (even if he restarts)...
no error in the console tho. If you use Feather on you you keep your level 90.
You don't this bug if you're under 90...

We see a level 1 when we are dead...

**Screenshots**
![image](https://user-images.githubusercontent.com/9601851/97843963-4300ed00-1c8e-11eb-96cb-f083b27329e4.png)
![image](https://user-images.githubusercontent.com/9601851/97844010-58761700-1c8e-11eb-89b7-986afd154d54.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version : Debian 9

**Comment by JoeAlisson** [comment]
Which class ?

I tried some, but it's working fine

![Screenshot from 2020-11-04 17-15-51](https://user-images.githubusercontent.com/5034192/98163575-c2c2cd80-1ec1-11eb-8b5e-d889478e7e03.png)

![Screenshot from 2020-11-04 17-16-24](https://user-images.githubusercontent.com/5034192/98163583-c5252780-1ec1-11eb-84ed-0f9e7e072753.png)

**Comment by Forcecat01** [comment]
![2](https://user-images.githubusercontent.com/54755997/98205971-25f84280-1f4a-11eb-8b6e-8571dabaf22c.png)
![1](https://user-images.githubusercontent.com/54755997/98205976-27296f80-1f4a-11eb-8f6a-5be61655a21c.png)

Same thing, all right.

**Comment by ryclos** [comment]
This is when you die with lvl 90 and you click "to village."
Before a moment is it working but now... Impossible to fixed that.
Cat have the same anomaly that my server haha



Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : Alisson Oliveira <notifications@github.com>
Date : 04/11/2020 10:19 (GMT-10:00)
À : JoeAlisson/L2jOrg <L2jOrg@noreply.github.com>
Cc : ryclos <loogle@hotmail.com>, Author <author@noreply.github.com>
Objet : Re: [JoeAlisson/L2jOrg] Lvl 90 to Lvl 1 When you die and click "to village" (#465)


Which class ?

I tried some, but it's working fine

[Screenshot from 2020-11-04 17-15-51]<https://user-images.githubusercontent.com/5034192/98163575-c2c2cd80-1ec1-11eb-8b5e-d889478e7e03.png>

[Screenshot from 2020-11-04 17-16-24]<https://user-images.githubusercontent.com/5034192/98163583-c5252780-1ec1-11eb-84ed-0f9e7e072753.png>

**Comment by JoeAlisson** [comment]
![output](https://user-images.githubusercontent.com/5034192/98284661-34615100-1f80-11eb-8326-cdba26e8a4a7.gif)

**Comment by ryclos** [comment]
Oooooh ok, this is maybe because i have false the delevel.. Maybe Cat too. Try to put false the delevel :)



Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : Alisson Oliveira <notifications@github.com>
Date : 05/11/2020 09:02 (GMT-10:00)
À : JoeAlisson/L2jOrg <L2jOrg@noreply.github.com>
Cc : ryclos <loogle@hotmail.com>, Author <author@noreply.github.com>
Objet : Re: [JoeAlisson/L2jOrg] Lvl 90 to Lvl 1 When you die and click "to village" (#465)


[output]<https://user-images.githubusercontent.com/5034192/98284661-34615100-1f80-11eb-8326-cdba26e8a4a7.gif>

**Comment by xcelebration** [comment]
sometime die it exp is reset to 0 on database lv will go 1
