### ISSUE TITLE
How to debug gradle appliction in eclipse？

### ISSUE THREAD

**Issue by fmpoffice** [JoeAlisson/L2jOrg#466]
how to debug appliction gradle in eclipse ?

**### I try IntelliJ IDEA is OK ，but   I want to understand  gradle in eclipse how to debug？**

![eclipse](https://user-images.githubusercontent.com/11001031/99529458-cd5d8680-29da-11eb-9fd4-a2108ca01676.jpg)

![ide](https://user-images.githubusercontent.com/11001031/99529487-da7a7580-29da-11eb-827e-452b5bf5bd63.jpg)

**Comment by vicochips** [comment]
I'm not sure eclipse can do it as intellij does it

**Comment by JoeAlisson** [comment]
Hi, this should work:

https://discuss.gradle.org/t/how-do-you-attach-a-debugger-to-gradle-so-that-i-can-debug-it-running-a-task/7526/5

**Comment by fmpoffice** [comment]
> Hi, this should work:
> 
> https://discuss.gradle.org/t/how-do-you-attach-a-debugger-to-gradle-so-that-i-can-debug-it-running-a-task/7526/5

благодарить
