### ISSUE TITLE
trigger skill

### ISSUE THREAD

**Issue by Forcecat01** [JoeAlisson/L2jOrg#470]
There is a question about how skills work with a skill trigger.

I implement skill 51457, and for it the trigger skill 51460 and faced such a problem

using trigger-skill-by-magic 
is called in case of attack of physical or magic skills, as well as when applying buffs or using any enhancements, even when using a teleport, the skill trigger is called. ideally, it should be called only when using physical or magician skills on the enemy.

is it possible to make a restriction so that it would not be called when using buffs, other actions? only when attacking the target

https://www.youtube.com/watch?v=n84ZWJsIFSc

![Screenshot_2](https://user-images.githubusercontent.com/54755997/100914434-1be34880-34e4-11eb-92f9-7065ed33de1e.png)

![Screenshot_3](https://user-images.githubusercontent.com/54755997/100914459-26054700-34e4-11eb-98fb-48850ec81e9b.png)

            <trigger-skill-by-magic skill="51460" target="MY_PARTY">
                <power initial="1"/>
                <chance initial="40"/>
                <types>PHYSIC MAGIC</types>
            </trigger-skill-by-magic>

**Comment by JoeAlisson** [comment]
Hi, triggered skills by attack must be use the  _trigger-skill-by-attack_ effect. Can you try with this one ?

        <trigger-skill-by-attack skill="51460" target="MY_PARTY">
            <power initial="1"/>
            <chance initial="40"/>
            <min-damage initial="10"/>
        </trigger-skill-by-attack>

**Comment by Forcecat01** [comment]
> Hi, triggered skills by attack must be use the _trigger-skill-by-attack_ effect. Can you try with this one ?
> 
> ```
>     <trigger-skill-by-attack skill="51460" target="MY_PARTY">
>         <power initial="1"/>
>         <chance initial="40"/>
>         <min-damage initial="10"/>
>     </trigger-skill-by-attack>	
> ```

if I use it like this, the skill trigger is called only during auto attack, there is no call with physical and magic skills

	    <trigger-skill-by-attack skill="51460" target="MY_PARTY">
                <power initial="1"/>              
                <chance initial="60"/>                  
                <min-damage initial="1.0"/>			
            </trigger-skill-by-attack>

maybe I missed something, please tell me

**Comment by JoeAlisson** [comment]
I'll check it
