### ISSUE TITLE
Initial Equipment

### ISSUE THREAD

**Issue by IIMelkorII** [JoeAlisson/L2jOrg#473]
The Initial Equipment is only working for humans, and not for other types of characters:
![image](https://user-images.githubusercontent.com/75391159/101021397-a365a180-354e-11eb-9455-449501b07107.png)

Humans:
![image](https://user-images.githubusercontent.com/75391159/101021280-7adda780-354e-11eb-9a34-bc0033694b0e.png)

Others:
![image](https://user-images.githubusercontent.com/75391159/101021317-8a5cf080-354e-11eb-8f36-0b1d785f0a87.png)

**Comment by vicochips** [comment]
Hello, 

Just add what u want in initialEquipmentEvent.xml (datapack/stats)

This is a custom feature

**Comment by IIMelkorII** [comment]
I didn't know that you could make a definition for each class. Thank you
