### ISSUE TITLE
MaxFreeTeleportLevel

### ISSUE THREAD

**Issue by GPADILHACARDOSO** [JoeAlisson/L2jOrg#475]
**Describe the bug**
Dont matter the number you set, he always take lvl 40 for start pay for teleports.

**To Reproduce**
1. Go to 'character.properties'
2. Set any n below 40 on 'MaxFreeTeleportLevel'
3. Test in game

**Expected behavior**
0 for take it off, and start from 1, take the parameter to set maximun lvl for free teleports.

**Comment by Bru7aLMike** [comment]
TeleportHolder.java uses its own TeleportLocation.java located at *\model\teleporter\TeleportLocation.java and works only on teleports which use the custom-made NPC teleport template. Meanwhile, the global teleporter window seems to be using another format, namely  *\model\TeleportLocation.java.

How to reproduce:
(1)
  - set Config.MAX_FREE_TELEPORT_LEVEL = 0
  - reload config or restart your server for the changes to take effect
  - continue with (2)
(2)
 - /target %self
 - //set_level 45         (anything more than 40 but less than 89)
 - delete all of the Adena from your character
 - create a clan and set its level to 5
 - give yourself Giran castle
 - teleport to your new castle
 - talk to the Chamberlain in the castle's throne room
 - upgrade your castle's teleport capabilities to level 2
 - continue with (3)
(3)
 - open Chamberlain's teleport menu and check whether they require you to pay 500 Adena or not.
(4)
  - set Config.MAX_FREE_TELEPORT_LEVEL = 90
  - reload config or restart your server for the changes to take effect
  - /target %self
  - //set_level 90
 - teleport to your new castle
 - talk to the Chamberlain in the castle's throne room
 - upgrade your castle's teleport capabilities to level 2
 - get back to (3)

**Comment by Bru7aLMike** [comment]
STATUS: RESOLVED!
