### ISSUE TITLE
Wepon Master Kamael given extra atk dmg and not the atk spd

### ISSUE THREAD

**Issue by GPADILHACARDOSO** [JoeAlisson/L2jOrg#479]
https://l2central.info/classic/%D0%93%D1%80%D0%B5%D1%88%D0%BD%D0%B8%D0%BA 
https://lineage2.plaync.com/dic/l2/skill/?=&itemid=&skillid=463&raceid=5&classid=
https://l2wiki.com/classic/Kamael_Soldier

All DB show 30 atk and 20 atk.spd... find this issue in file 00400-00499.xml

   <skill id="463" name="Weapon Mastery" max-level="5">
        
        <icon initial="icon.skill0816"/>
        <attributes property="MAGIC" magic-critical-rate="5.0">
        </attributes>
        <target/>
        <effects>
            <stat-modify stat="PHYSICAL_ATTACK">
                <power initial="30.0">
                    <value level="2">50.0</value>
                    <value level="3">70.0</value>
                    <value level="4">130.0</value>
                    <value level="5">200.0</value>
                </power>
            </stat-modify>
            <stat-modify stat="PHYSICAL_ATTACK">
                <power initial="20.0">
                    <value level="2">30.0</value>
                    <value level="3">40.0</value>
                    <value level="4">80.0</value>
                    <value level="5">100.0</value>
                </power>
            </stat-modify>
        </effects>
    </skill>

for this one 

    <skill id="463" name="Weapon Mastery" max-level="5">
        
        <icon initial="icon.skill0816"/>
        <attributes property="MAGIC" magic-critical-rate="5.0">
        </attributes>
        <target/>
        <effects>
            <stat-modify stat="PHYSICAL_ATTACK">
                <power initial="30.0">
                    <value level="2">50.0</value>
                    <value level="3">70.0</value>
                    <value level="4">130.0</value>
                    <value level="5">200.0</value>
                </power>
            </stat-modify>
            <stat-modify stat="PHYSICAL_ATTACK_SPEED">
                <power initial="20.0">
                    <value level="2">30.0</value>
                    <value level="3">40.0</value>
                    <value level="4">80.0</value>
                    <value level="5">100.0</value>
                </power>
            </stat-modify>
        </effects>
    </skill>

its based on power and not per(centage) so gives the correct amount.

**Comment by MaJr-Dp** [comment]
A simpler explanation should be written.
a lot of lyrics)))

**Comment by GPADILHACARDOSO** [comment]
Its is not a asking for fix... it is the fix. I just dont know how to send(never used Git before), So i use here.
