### ISSUE TITLE
Auto Use Buff BUG

### ISSUE THREAD

**Issue by GPADILHACARDOSO** [JoeAlisson/L2jOrg#487]
**Describe the bug**
If u put one auto buff on bar and turn in on, it will only trigger if u are in auto hunt.

**To Reproduce**
1. Take a auto use skill
2. Put on bar and turn on
3. Turn on Auto Hunt
4. After start hunt the buff will trigger

**Expected behavior**
Auto use buff need trigger in all zones excluding peace zone.

**Comment by vicochips** [comment]
Try on retail, it works the same

**Comment by GPADILHACARDOSO** [comment]
https://youtu.be/wXdA3O1O1RU

Looks like i'm right... i download NA Classic and play with my old char. 

It have 1 buff with auto use. In the video it is turned on but i city nothing happen cause in peace zone, when it change to general she buff automatic.

**Comment by vicochips** [comment]
Ok I didnt understood what kind of buff you were talkign about.

**Comment by GPADILHACARDOSO** [comment]
Np... ty for update to bug

**Comment by vicochips** [comment]
I have done a fix :)
