### ISSUE TITLE
[AuthServer]Incorrect close of connection.

### ISSUE THREAD

**Issue by lordofdest** [JoeAlisson/L2jOrg#61]
**Describe the bug**
AuthServer doesn`t send LoginFail before close connection as result client waiting for response...

**To Reproduce**
Open client.
Try to the server with incorrect login. (123)

**Network.log**
(16:42:00) Log: Log file open, 05/02/19 16:42:00
(16:42:00) Log: (SendAuth)[NONE] RequestAuthLogin
(16:42:02) Log: (ReceiveAuth)[AC_PROTOCOL_VER] ProtocolVersionPacket
(16:42:02) Log: (SendAuth)[AQ_GAMEGUARD] ResponseAuthGameGuard
(16:42:03) Log: (ReceiveAuth)[AC_GAMEGUARD] AuthGameGuardPacket
(16:42:03) Log: (SendAuth)[AQ_LOGIN] RL

**Screenshots**
[Image](http://prntscr.com/njir2r)

**Comment by JoeAlisson** [comment]
Its seems a Java bug  on Windows environment. Anyway I'll be working on a fix.

![Image](https://i.imgur.com/PTeoRfo.png)
