### ISSUE TITLE
MP Recovery Potion (Novice) não funciona

### ISSUE THREAD

**Issue by HityZ** [JoeAlisson/L2jOrg#67]
O [MP Recovery Potion (Novice)](https://l2wiki.com/classic/MP_Recovery_Potion_(Novice)) não tem nenhum efeito e nem é consumido, não sei nada a respeito da recuperação do mesmo.

**Comment by xavierceo** [comment]
Já foi resolvido então na versão 1.3.0 da l2jbrasil?
