### ISSUE TITLE
Magic skill Varka, Ketra, Hot Springs

### ISSUE THREAD

**Issue by Forcecat01** [JoeAlisson/L2jOrg#70]
Hello. 
there is a problem with using magician skills on monsters in the locations of Varka, Ketra, Hot Springs. auto attack and skills from physical skills work great. but the Magic skills on monsters do not inflict damage. how to deal with it?

**Comment by JoeAlisson** [comment]
which is the player'a level and the monster's level ?

There are some configuration that increase the monster's magic resist based on  level diff in the file Npc.ini:

# "When a character's level is 3 or more levels lower than that of a monsters level the chance that the monster will be able to resist a magic spell will increase."
# Notes:
#	If you want to disable this feature then set it 99
# Default: 78
MinNPCLevelForMagicPenalty = 78

# The penalty in percent for -3 till -6 level differences
# Default: unknown
SkillChancePenaltyForLvLDifferences = 2.5, 3.0, 3.25, 3.5

Can you check if is something related to this ?

**Comment by Forcecat01** [comment]
I understood you. Now I will test on equal levels

**Comment by Forcecat01** [comment]
Thanks, the problem was due to the level. just made level 77 and the damage appeared from a skill mage. 

Special thanks for the settings.

http://prntscr.com/p6ycft
