### ISSUE TITLE
Implement New Teleport System

### ISSUE THREAD

**Issue by JoeAlisson** [JoeAlisson/L2jOrg#72]

**Comment by MaJr-Dp** [comment]
Need to update system:

The teleportation system's been upgraded.
Now: teleportation is happening in during 2 seconds (goes visual castes skill)
More not perhaps move in pvp of a (able aggression)

**Comment by MaJr-Dp** [comment]
Changes 18.09.19 (Omg)))
From now on the teleportation with help of NPC comes with animation similar to the one that was previously shown in cases of teleportation with the Scroll of Escape and happens after a 2-second lag.

https://eu.4game.com/patchnotes/lineage2classic/184/
