### ISSUE TITLE
Attributes system and adding attributes to new npc in zones

### ISSUE THREAD

**Issue by vicochips** [JoeAlisson/L2jOrg#81]
Hello

- [x] An attribute is available for characters level 40 and above;

— Spirits can evolve up to lvl 5;

— When the attribute fragment gets extracted, Spirit loses 1 evolution lvl;

- [x]  Spirits evolved to lvl 1 -2 receive 1 skill point with each level up and spirits evolved to lvl 3 - 5 receive 2 skill points;

— An attribute information is displayed in the monster target window;

— An attribute damage in relation to each other has been changed:

Attribute influence | Bonus damage (base damage - 100)
-- | --
Prevailing attribute | 130
The same attribute | 110
Neither prevailing or weak | 110
Weak attribute | 110
No attribute | 100

Zones attributes: 

- [x] Sea of Spores | Water
- [x] War-Torn Plains | Water
- [x] Ivory Tower Crater | Wind
- [x] Plains of Glory | Wind
- [x] The Patriot's Necropolis | Wind
- [x] Enchanted Valley | Earth
- [x] Silent Valley | Earth
- [x] Fields of Massacre | Earth
- [x] Necropolis of Devotion | Earth
- [x] Forgotten Island | Earth
- [x] Cemetery | Fire
- [x] Blazing Swamp | Fire
- [x] Devils Isle | Fire

**Comment by vicochips** [comment]
https://l2wiki.com/classic/Daymen

**Comment by MaJr-Dp** [comment]
I propose to rent a separate file where the NPC will be recorded, the attribute to which it relates and the amount of spontaneous experience from this NPC.
ps at your discretion.

**Comment by vicochips** [comment]
Why not, but actually the system is in place with attributes zones (fog, etc), just have to add some tag to npc id

**Comment by vicochips** [comment]
I have updated the post
