### ISSUE TITLE
Soulshot

### ISSUE THREAD

**Issue by vicochips** [JoeAlisson/L2jOrg#82]
- [x] Soulshots and Spiritshots now have the same grade; 
- [x] A player can use only one type of Soulshots and Spiritshots regardless of his weapons' grade;  
- [x] New Soulshots and Spiritshots are sold by Grocers NPC in every town. They can also be obtained via Vitamin Manager by exchanging Soulshots Coupons;
- [x] The weight of new Soulshots and Spiritshots is zero;
- [x] New Soulshots and Spiritshots have the following restrictions:

**Comment by JoeAlisson** [comment]
I edited your issue to put a task list to be more clear.

I think 1, 2 and 3 was already fixed, can you test it ?

Can you describe the missing restriction ?

**Comment by vicochips** [comment]
Item
	
Restrictions
Soulshots	

Can be destroyed / Can be stored in a private warehouse.

Cannot be exchanged / dropped / sold / stored in a clan warehouse.
Spiritshots
Blessed Soulshots
Blessed Spiritshots

 

— The number of Soulshots consumed during the fight has changed:
Weapon
	
Grade
	
Consumption
All weapons except bows	No grade, D, C	1
B	2
A	3
S	4
Bows	No grade, D, C	2
B	3
A	4
S	5

 

— If weapon hits multiple targets the consumption increases depending on the number of targets:
Number of targets
	
Consumption
1~3	х 1 
4~8	х 2 
9~14	х 3 
15~20	х 4

 

— The old recipes of Soulshots and Spiritshots can no longer be received by hunting and spoiling;

— The existing recipes can be sold in shops. The old recipes will be deleted during the maintenance after the update. Exact dates will be announced additionally;

— Here is the list of recipes which will be deleted from the game:
*Recipes of Soulshot (D ~ S grade) (100%)
*Recipes of Spiritshot (D ~ S grade) (100%)
*Recipes of Blessed Spiritshot (D ~ S grade) (100%)
*Recipes of Blessed Soulshots (D ~ S grade) (100%)
*Recipes of Soulshot Compressed Package (D ~ A grade) (100%)
*Recipes of Spiritshot Compressed Package (D ~ A grade) (100%)
*Recipes of Blessed Spiritshot Compressed Package (D ~ A grade) (100%)
*Recipes of Greater Compressed Package of Soulshots (D ~ A grade) (100%)
*Recipes of Greater Compressed Package of Spiritshots (D ~ A grade) (100%)
*Recipes of Greater Compressed Package of Blessed Spiritshots (D ~ A grade) (100%)

 

— The old Soulshots and Spiritshots can no longer be used. Players can exchange them to the new ones via Vitamin Manager. The old items will be deleted during the maintenance after the update. Exact dates will be announced additionally; 

— Here is the list of items which will be deleted:
*Soulshot (NG ~ S grade) and all the Compressed Packages and Greater Compressed Packages of these Soulshot.
*Spiritshot (NG ~ S grade) and all the Compressed Packages and Greater Compressed Packages of these Spiritshot.
*Soulshot and Spiritshot (No-grade) (Novice).
*Blessed Spiritshot (NG ~ S grade) and all the Compressed Packages and Greater Compressed Packages of these Spiritshot.
*Blessed Soulshot (NG ~ S grade).
*Mysterious Soulshot (NG ~ S grade) and all the Packages of these Soulshot.
*Mysterious Spiritshot (NG ~ S grade).
*Mysterious Blessed Soulshot (NG ~ A grade).
*Mysterious Blessed Spiritshot (NG ~ С grade) and all the Packages of these Spiritshot

 

— The description of the items "Spirit Ore" and "Soul Ore" has been modified due to the changes of Soulshots and Spiritshots system.
