### ISSUE TITLE
Stats management system

### ISSUE THREAD

**Issue by MaJr-Dp** [JoeAlisson/L2jOrg#84]
235 Prot
Stats management system
Basic stats management system has been added.

76+ lvl characters gain Characteristics Points when level up;
Obtained Characteristics Points can be proceeded in Character Status window (Alt + T ); — Points can be retrieved with payment by resetting the stats via Reset button;
When reset all points return back;
Reset price - 200 L-Coin and 100 000 Adena;
When reaching certain characteristics values a bonus passive skill activates;
List of bonus skills is available in stats management window (Effects button);
There are 3 levels of bonus passive skills:

Characteristic | Bonus skills Lv.1 | Bonus skills Lv.2 | Bonus skills Lv.3

STR 60 | P.Atk. +20 | 70 | P. Skill Critical Damage +200 | 90 | P. Skill Power +10%
INT 60 | M.Atk. +20 | 70 | M. Skill Critical Damage +200 | 90 | M. Skill Power+10%
DEX 50 | P. Critical Rate +50 | 60 | P. Skill Cooldown -10% | 80 | P. Skills Evasion +20%
WIT 40 | M. Critical Rate +50 | 50 | M. Skill Cooldown -10% | 70 | M. Skills Evasion +20%
CON 50 | P. Def. +200 | 65 | Max HP +1000 | 90 | HP Recovery +10
MEN 45 | M. Def. +200 | 60 | Max MP +1000 | 85 | MP Recovery +10

https://eu.4game.com/patchnotes/lineage2classic/184/

**Comment by JoeAlisson** [comment]
Anyone knows how much points is gained at each level ?

**Comment by vicochips** [comment]
It seems to be 1 point by level so from level 76 to 85 -> 10 pts
