### ISSUE TITLE
Add system: Use Potion Automatically \ Auto-consume supplies

### ISSUE THREAD

**Issue by MaJr-Dp** [JoeAlisson/L2jOrg#85]
Auto-consume supplies
— Some supplies can be auto-chosen;

— In order to auto-consume supplies, it is necessary to move an item icon to the special cell in the automation window and press the “On/Off” button to activate auto-use;

— A player can choose which concrete supplies should be automated by right clicking on the items icon in the automation window;

— At the same time only 12 items can be set with the purpose of auto-use;

— If a character is in a peaceful zone, auto-consume supplies stops working until the character leaves this zone.

Use Potion Automatically
— Auto-use allows automatic use of HP Potions;

— Individual interface for the potion auto-use has been added; 

— On a special scale it is possible to configure the HP value, when Potions are being auto-used

(by default 80% HP);

— Potions that can be auto-used are marked with “Auto Use Potion” text;

— Cell for potion can be activated/deactivated within right clicking on the cell.

https://eu.4game.com/patchnotes/lineage2classic/154/

**Comment by vicochips** [comment]
This system is link with auto farm system right?

**Comment by JoeAlisson** [comment]
@vicochips Yes

**Comment by JoeAlisson** [comment]
Related to #77
