### ISSUE TITLE
Initial Quests - Tutorial Not working properly

### ISSUE THREAD

**Issue by AlegriaFerrato** [JoeAlisson/L2jOrg#89]
Hi bro, I didn't know which section to use and will write here.
I am using your sources Classic Kamael(228), and I would like to ask how you can increase the Protocol from 228 to 245, so that i can use the new game client.
I hope you will give an answer in advance thank you very much.

**Comment by JoeAlisson** [comment]
You can use the code from branch 'develop'. It contains initial support to 245 protocol

**Comment by AlegriaFerrato** [comment]
oh,ok thanks you. <3

**Comment by AlegriaFerrato** [comment]
error loading sql file 1_characters
ERROR 1146 <42S02> at line 77: Table 'l2db.clan_data' doesn't exist
cmd errors : loading character_quests
Error 1826 <HY000> in line 2: duplicate foreign key constraint name 'FK_FRIENDS_FRIEND'
this error occurs while loading these sql files : character, quests, character_recipe book, character_recipe store list, character_relationship, character, skills, character_subclasses, 
 what is the problem?..
thx

**Comment by AlegriaFerrato** [comment]
warn  gameserver in character selection
[ClientPacketHandler: unknownPacket: 54] unknown package (REQUEST_USER_BAN_INFO): d0-00000000 D05E0198810000.
I enter the security code in the client and the game closes with crash error

**Comment by JoeAlisson** [comment]
This Warning is not related with the crash. 
To fix the crash you must enable the secondary auth on your system or disable it on the server (secondary-auth.xml)

**Comment by AlegriaFerrato** [comment]
Well now I'll try, but how can I remove warn from the game server?

**Comment by JoeAlisson** [comment]
There is two ways to remove it, the right way is to implement the packet :). 

The other is to configure the log4j.xml file not to show it:
Add on Loggers:

```
<Logger name="org.l2j.gameserver.network" level="error">
       <AppenderRef ref="game"/>
       <AppenderRef ref="debug"/>
</Logger>
```

Although I don't recommend  to remove it. It exists to help with development to know which client packets are not implemented yet.

**Comment by AlegriaFerrato** [comment]
Okay, I noticed a bug, the quest at the very beginning of "how to control a character" can not be closed, when the character moves, it resumes along with the voice assistant, check :-)
I run testing sources now :))
