### ISSUE TITLE
Mini Bug Report "development"

### ISSUE THREAD

**Issue by AlegriaFerrato** [JoeAlisson/L2jOrg#90]
(SOURCES BRANCH GIT "DEVELOPMENT" protocol 245)
I looked at the source code, I will make a small bug report, I hope I will help you with something!

- [ ] 1. Non-working skills at kamaels ( animations, non damage, non target , animation  on itself )
- [x] 2. Olympiad Manager does not work no HTML
- [ ] 3. No no chain of quests beginners
- [x] 4. Constant pop-up of the "how to control a character" window when moving at the beginning.
- [x] 5. Dominator imposes debuffs on itself.
Just minor bugs that are corrected in xml( talismans, bracelets, points, quivers, etc.)
I hope it will be useful for the developer.
I am very interested in working with your sources, thank you for your work!
I have a small question, what is the maximum online server can withstand?
(SOURCES BRANCH GIT "DEVELOPMENT" protocol 245)

**Comment by AlegriaFerrato** [comment]
Bug report on the characters 'skills, branch "development" (245 protocol)
1. Thunder Storm (Warolrd) - stun itself When used
2. Sonic Focus (Gladiator) - Charges only for the 1st level
3. Mass Shackling (Paladin) - when using debafaet roots on itself
4. Sanctuary (Paladin) - Debuff overlays itself
5. Horror(Hell Knight) - no fear target
6. Silent Move(Adventurer) - the Character does not hide.
7. Cancellation(Sorc\MM) - no cancel buff target
8. Cleanse (Bishop) - Does not remove debuff from target
9. Requiem(Bishop) - when used, the character debuffs itself
10. Holy Aura (Eva Templar) - Used on itself
11. Death Sting(Moonlight Sentinel) - when used, mage silence is not applied (0 of 15 shots)
12. Judgment(Shillen Knight) - No debuff effect, + mass skill (like it should be a single target)
13. Aura of Hate (Shillen Knight) - Agression is imposed on itself.
14. Recharge(SE\EE) - Used by itself
[Test 10.03.2020.]

**Comment by MaJr-Dp** [comment]
Good afternoon.
JoeAlisson

I can help with fitbacks (a list of unsold content and subtleties.
Things like: Locations \ items \ skills.
Correction: Skills / items - it’s not so difficult to describe * the client * \ patch *.

If you are interested in this, give the answer: how do you see it, do you need it?

*Google-tr*

**Comment by JoeAlisson** [comment]
@AlegriaFerrato Thank you for reports. I edited yours comments to put a task list to be easy to mark it as fixed :)

@MaJr-Dp Sure it will help a lot

**Comment by AlegriaFerrato** [comment]
I have not yet completed the tests on the classes, as soon as I finish and identify more bugs, I will inform you.

**Comment by AlegriaFerrato** [comment]
Hi:),how are you?)
I will send a new bug list soon.

**Comment by AlegriaFerrato** [comment]
Hi Joe, i download your update sources.
And compiling, install database.
When i create character, character created  0 hp/mp/cp,
gameserver error: 
Error While running packet org.l2j.gameserver.network.clientpackets.CharacterCreate from client. [account: admin - IP: my ip ]
Caused by : java.sql.SQLException: Field 'player_id' doesn't have a default value..
what the problem? help me please.

**Comment by JoeAlisson** [comment]
Hi, Alegria.
Thank you for report. Just fixed it.

**Comment by AlegriaFerrato** [comment]
Bug report from 19.03.2020: 
Skills: 

- [ ] 1. Sonic Rage-Duelist: Does not apply debuff P. Def -30% 
- [ ] 2. Dual Weapon Defense-Duelist: P. Skill Evasion -40% but he  should +40% 
- [ ] 3. Panther Fatal Claw-Pet Hell Knight: Does no damage 
- [ ] 4. Shadow Step-Adventurer/Wind Rider/Ghost Hunter: Does not stun the target 
- [ ] 5. Clear Movements-Adventurer: does not reset cooldown skill Hide 
- [ ] 6. Sand Bomb-Adventurer/Wind Rider/Ghost Hunter: Does not lower M. Accuracy 
- [ ] 7. Cure Poison - Archmage/Mystic Muse: does not cure poisoning 
- [ ] 8. Mass Slow-Soultaker: Deals damage to the caster lol 
- [ ] 9. Cursed Blow - Cursed Man Pet Soultaker: it does Not deal damage 
- [ ] 10. Chain Heal-Cardinal: Not working 
- [ ] 11. Miracle-Cardinal: Not working 
- [ ] 12. Divine Power-Cardinal: Does not increase healing power +80 units 
- [ ] 13. Power Supremacy-Summoners: Works reduces HP but does not increase physical attack 
- [ ] 14. Deadly Strike - SWS/BD: Doesn't work with sword\blunt 
- [ ] 15. Armor Crush - Spoil\Maestro\the Titan : Work, but not work a sword, double handed weapon or spear 
- [ ] 16. Shillen's Cursed Field - Shillen Saint: a single skill, but must be massive
- [ ] 17. Mass Recharge - Shillien Saint : Not working 
- [ ] 18. Focus Force-Grand Khavatari: Charges to the first charge 
- [ ] 19. Skills Kamael - Doombringer\SH\Trickster: Almost all don 't work 
- [ ] 20. Excruciating Strike-Titan : Doesn't work with a two- handed sword 
- [ ] 21. Full Swing-Titan: Does not work with a two- handed sword 
- [ ] 22. Demolition Impact-Titan : Doesn't work with a two- handed sword 
- [ ] 23. Full Knockdown-Titan : Doesn't work with a two- handed sword

===============================================
Errors with bypass\packets and admin panel 

- [ ] 1-a clan is Not created via the admin panel: 

Exception during execution of ' admin_pledge create CLAN: java.lang.reflect.UndeclaredThrowableException 
When creating a clan the NPC has an error with bypass 

- [ ] 2 - when dismiss a character from the group error in the gameserver console: 

org.l2j. gameserver.network.clientpackets.RequestOustPartyMember@36f64c8 from client [Player: AlegriaFerrato[33172] - Account admin - ip my ip] 
[ [Error] [Client Packet:run:39]: null 
at org.l2j. gameserver/opt.l2j. gameserver.model.Party.remove Party Member<Party.java:406>

**Comment by vicochips** [comment]
Just one comment for now: 

`Dual Weapon Defense-Duelist: P. Skill Evasion -40% but he should +40% ` 

Is it 30% : For 1 min., P. Skill Evasion +30%. Requires a dual sword.

**Comment by vicochips** [comment]
hey ! for dual weapon defense, skill seems to be good

```
<stat-hp-based stat="EVASION_RATE" stat-add="EVASION_RATE" hp-percent="0" mode="PER">
				<power initial="30.0">
					<value level="2">35.0</value>
					<value level="3">40.0</value>
				</power>
			</stat-hp-based>
```

**Comment by AlegriaFerrato** [comment]
> hey ! for dual weapon defense, skill seems to be good
> 
> ```
> <stat-hp-based stat="EVASION_RATE" stat-add="EVASION_RATE" hp-percent="0" mode="PER">
> 				<power initial="30.0">
> 					<value level="2">35.0</value>
> 					<value level="3">40.0</value>
> 				</power>
> 			</stat-hp-based>
> ```
> 
> For shadow step: there is stun in skill so ... ?
> 
> ```
> 
> <abnormal type="STUN" visual="STUN" >
> 			<level initial="2"/>
> 			<time initial="1"/>
> 			<chance initial="70"/>
> 		</abnormal>
> ```
> 
> Clear Movements: skill does not exist in datapack


Yes, shadow step stun character, but he not work((
![26BE608E-7AFD-42FE-8626-9646B6A286A2](https://user-images.githubusercontent.com/61910218/77161527-f54ac200-6aba-11ea-8d43-e9535b13fcaa.png)

**Comment by JoeAlisson** [comment]
@AlegriaFerrato Cure Poison is working fine. Maybe in your test the abnormal level of Poison was greater than effect's power of Cure Poison. Can you check it ?

**Comment by AlegriaFerrato** [comment]
> ure Poison is working fine. Maybe in your test the abnormal level of Poison was greater than effect's power of Cure Poison. Can you check it ?

t probably was then, and I'll check again as soon as I'm free.

**Comment by AlegriaFerrato** [comment]
hmm. i'm update sources.
and i start game server, error loading [Cache]
---------------------------------------------------------
Exception in thread "main" java.land.ExceptionInitailizerError
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that curresponds to your MySQL server verision for the right syntax to use near 'cr.id NOT IN <
SELECT crest_id AS id FROM clan_data <
UNION ALL
, at line 1
---------------------------------------------------------
use mysql 8.0

**Comment by JoeAlisson** [comment]
@AlegriaFerrato Did you update the crest table ?

**Comment by AlegriaFerrato** [comment]
> @AlegriaFerrato Did you update the crest table ?

I just download new sources, delete my database and installing new again

**Comment by JoeAlisson** [comment]
I don't know what is going on with your MySql. It should works since you are using the MySql 8. I know previous versions do not accept table aliases on delete statement  but the newer does:

[https://dev.mysql.com/doc/refman/5.7/en/delete.html](Mysql 5.7)
[https://dev.mysql.com/doc/refman/8.0/en/delete.html](Mysql 8)

Anyway I removed the table alias must works fine now.

**Comment by AlegriaFerrato** [comment]
> I don't know what is going on with your MySql. It should works since you are using the MySql 8. I know previous versions do not accept table aliases on delete statement but the newer does:
> 
> [https://dev.mysql.com/doc/refman/5.7/en/delete.html](Mysql 5.7)
> [https://dev.mysql.com/doc/refman/8.0/en/delete.html](Mysql 8)
> 
> Anyway I removed the table alias must works fine now.

Ok, I now re-install MySQL and Server.

**Comment by AlegriaFerrato** [comment]
1- Clan boss rewards (abundance) do not work

2- NPCs do not work near the locks for registration
3 - Administrator lock control menu - siege information does not work)
4- The game menu of the Castles does not work.
5 - Castle defenders cannot be hit without the CTRL key (massive skills and spear and simple punch)
