### ISSUE TITLE
Question about skills

### ISSUE THREAD

**Issue by vicochips** [JoeAlisson/L2jOrg#94]
Hello just a little question, for example Skill prominence: 

`level 36: Detonates flames to inflict damage on the enemy with bonus 148 M. Atk. Power.`

but the skill is : 
```
	<magical-attack-range>
                    <power>
			<value level="36">118.0</value>
				</power>
				</magical-attack-range>
```

We are agree that the power is not good ?

**Comment by JoeAlisson** [comment]
Yes. Although I parsed all description and some attributes from client files. The skill's effects is not that easy, so we need to check all effects since none of it was updated yet.

**Comment by phamminh88** [comment]
How do I contact you? I want to contribute to this project

**Comment by vicochips** [comment]
Hello, the best way to contribute is to do some pull request I think (right Joe ?) ! In what way do you want to contribute ?

**Comment by JoeAlisson** [comment]
> How do I contact you? I want to contribute to this project

You can Contact me through discord : JoeAlisson#4309

> Hello, the best way to contribute is to do some pull request I think (right Joe ?) ! In what way do you want to contribute ?

Yes. The pull request is a good way :)
