### ISSUE TITLE
Info: Trello invite your mail

### ISSUE THREAD

**Issue by MaJr-Dp** [JoeAlisson/L2jOrg#96]
Created Trello in which there will be descriptions of systems, AI, Instances, Locations.
According to the information that I have and collect, occasionally there will be implementations of other teams (as a model).

https://trello.com/b/ZH6SI3dm/l2jorg

P.s. Who else invite?)

**Comment by vicochips** [comment]
hey :) , me please

**Comment by JoeAlisson** [comment]
Thanks, well done :)

**Comment by vicochips** [comment]
@MaJr-Dp can you invite me ? :)

**Comment by MaJr-Dp** [comment]
> @MaJr-Dp can you invite me ? :)

Give me your mail

**Comment by vicochips** [comment]
@MaJr-Dp hmm, victor.fraysse@epitech.eu

**Comment by MaJr-Dp** [comment]
Done

**Comment by vicochips** [comment]
thx bro :) , but why don't u use the "project tab of github" too ?

**Comment by MaJr-Dp** [comment]
Having 4/5 projects and from time to time scoring on them - you start to get confused in all this (different sources).
And Trello can always be opened and read)

**Comment by MaJr-Dp** [comment]
You have admin rights in Trello

**Comment by vicochips** [comment]
Ok good :)

**Comment by MaJr-Dp** [comment]
If you have a channel - give me a link

**Comment by MaJr-Dp** [comment]
https://discord.gg/udv2Vhg

**Comment by MaJr-Dp** [comment]
Do you have anything to open, new DAT patch files?
Or give an open 245+ protocol.)

**Comment by vicochips** [comment]
I don't understand the question :O

**Comment by MaJr-Dp** [comment]
Discord go)
