### ISSUE TITLE
How to build in Eclipse

### ISSUE THREAD

**Issue by phamminh88** [JoeAlisson/L2jOrg#99]
Hi Joe. Can you make new video or txt about how to build project in Eclipse ?

**Comment by vicochips** [comment]
yo ! you need gradle on eclipse, then to build : ./gradlew distZip on terminal

**Comment by JoeAlisson** [comment]
You also can use the eclipse interface to run the tasks

[Eclipse Buildship](https://www.eclipse.org/community/eclipse_newsletter/2018/february/buildship.php)
See the following sections: 
* Project Import;
* Task View  and task Execution;
